/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;

import Clases.Conectar;
import java.sql.Connection;
import javax.swing.JOptionPane;
/**
 *
 * @author sandybau
 */
public class Actualizar_ConsultorioR extends javax.swing.JFrame {
    Conectar conectarBD = new Conectar();
    /**
     * Creates new form Actualizar_ConsultorioN
     */
    public Actualizar_ConsultorioR() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Encabezado = new javax.swing.JPanel();
        EncabezadoActualizar_Consultorio = new javax.swing.JLabel();
        Cuerpo = new javax.swing.JPanel();
        Id_Consultorio = new javax.swing.JLabel();
        Id_Doctor = new javax.swing.JLabel();
        txtId_DoctorConsultorioA = new javax.swing.JTextField();
        txtId_ConsultorioA = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnBuscarConsultorio = new javax.swing.JButton();
        btnRegresarPaciente = new javax.swing.JButton();
        btnActualizarPaciente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Encabezado.setBackground(new java.awt.Color(0, 153, 255));

        EncabezadoActualizar_Consultorio.setFont(new java.awt.Font("Segoe UI Black", 0, 20)); // NOI18N
        EncabezadoActualizar_Consultorio.setForeground(new java.awt.Color(255, 255, 255));
        EncabezadoActualizar_Consultorio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EncabezadoActualizar_Consultorio.setText("ACTUALIZAR CONSULTORIO");

        javax.swing.GroupLayout EncabezadoLayout = new javax.swing.GroupLayout(Encabezado);
        Encabezado.setLayout(EncabezadoLayout);
        EncabezadoLayout.setHorizontalGroup(
            EncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EncabezadoLayout.createSequentialGroup()
                .addGap(229, 229, 229)
                .addComponent(EncabezadoActualizar_Consultorio)
                .addContainerGap(229, Short.MAX_VALUE))
        );
        EncabezadoLayout.setVerticalGroup(
            EncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EncabezadoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(EncabezadoActualizar_Consultorio, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        jPanel1.add(Encabezado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 60));

        Cuerpo.setBackground(new java.awt.Color(153, 204, 255));

        Id_Consultorio.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        Id_Consultorio.setForeground(new java.awt.Color(0, 51, 51));
        Id_Consultorio.setText("ID CONSULTORIO (5)");

        Id_Doctor.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        Id_Doctor.setForeground(new java.awt.Color(0, 51, 51));
        Id_Doctor.setText("ID DOCTOR (10)");

        txtId_DoctorConsultorioA.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtId_DoctorConsultorioA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtId_DoctorConsultorioAActionPerformed(evt);
            }
        });

        txtId_ConsultorioA.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtId_ConsultorioA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtId_ConsultorioAActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 153));
        jLabel1.setText("BUSCAR DOCTOR:");

        btnBuscarConsultorio.setBackground(new java.awt.Color(0, 153, 255));
        btnBuscarConsultorio.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnBuscarConsultorio.setText("BUSCAR");
        btnBuscarConsultorio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarConsultorioMouseClicked(evt);
            }
        });
        btnBuscarConsultorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarConsultorioActionPerformed(evt);
            }
        });

        btnRegresarPaciente.setBackground(new java.awt.Color(0, 153, 255));
        btnRegresarPaciente.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnRegresarPaciente.setText("REGRESAR");
        btnRegresarPaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegresarPacienteMouseClicked(evt);
            }
        });
        btnRegresarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarPacienteActionPerformed(evt);
            }
        });

        btnActualizarPaciente.setBackground(new java.awt.Color(0, 153, 255));
        btnActualizarPaciente.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnActualizarPaciente.setText("ACTUALIZAR");
        btnActualizarPaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnActualizarPacienteMouseClicked(evt);
            }
        });
        btnActualizarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarPacienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CuerpoLayout = new javax.swing.GroupLayout(Cuerpo);
        Cuerpo.setLayout(CuerpoLayout);
        CuerpoLayout.setHorizontalGroup(
            CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CuerpoLayout.createSequentialGroup()
                .addGroup(CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CuerpoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(Id_Doctor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtId_DoctorConsultorioA, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscarConsultorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(CuerpoLayout.createSequentialGroup()
                        .addGroup(CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CuerpoLayout.createSequentialGroup()
                                .addGap(99, 99, 99)
                                .addComponent(Id_Consultorio)
                                .addGap(31, 31, 31)
                                .addComponent(txtId_ConsultorioA, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(CuerpoLayout.createSequentialGroup()
                                .addGap(141, 141, 141)
                                .addComponent(btnActualizarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(112, 112, 112)
                                .addComponent(btnRegresarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(36, 36, 36))
        );
        CuerpoLayout.setVerticalGroup(
            CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CuerpoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtId_DoctorConsultorioA, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Id_Doctor)
                    .addComponent(jLabel1)
                    .addComponent(btnBuscarConsultorio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Id_Consultorio, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtId_ConsultorioA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegresarPaciente)
                    .addComponent(btnActualizarPaciente))
                .addGap(50, 50, 50))
        );

        jPanel1.add(Cuerpo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 740, 210));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void limpiarCajas(){
        txtId_DoctorConsultorioA.setText(null);
        txtId_ConsultorioA.setText(null);
    }
    private void txtId_DoctorConsultorioAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtId_DoctorConsultorioAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtId_DoctorConsultorioAActionPerformed

    private void txtId_ConsultorioAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtId_ConsultorioAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtId_ConsultorioAActionPerformed

    private void btnBuscarConsultorioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarConsultorioMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarConsultorioMouseClicked

    private void btnBuscarConsultorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarConsultorioActionPerformed
        Connection con = null;
        try {
            con = conectarBD.getConnection();
            conectarBD.ps = con.prepareStatement("SELECT * FROM consultorio WHERE Id_Doctor = ?");
            conectarBD.ps.setString(1, txtId_DoctorConsultorioA.getText());
            
            conectarBD.rs = conectarBD.ps.executeQuery(); //TRAER LOS RESULTADOS DE LA CONSULTA
            if(conectarBD.rs.next()){
                txtId_ConsultorioA.setText(conectarBD.rs.getString("Id_Consultorio"));
            }else{
                JOptionPane.showMessageDialog(null, "NO SE ENCONTRARON RESULTADOS");
            }
            //EJECUTAR LA CONSULTA
            int res = conectarBD.ps.executeUpdate();
            if(res > 0){
                JOptionPane.showMessageDialog(null, "CONSULTORIO ACTUALIZADO");
                limpiarCajas();
            }
            else{
                JOptionPane.showMessageDialog(null, "ERROR AL ACTUALIZAR CONSULTORIO");
                limpiarCajas();
            }
            //CERRAR BD
            con.close();
        } catch (Exception e) {
            System.err.println("Error: "+e);
        }
    }//GEN-LAST:event_btnBuscarConsultorioActionPerformed

    private void btnRegresarPacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarPacienteMouseClicked
        PrincipalRecepcionista nuevaV = new PrincipalRecepcionista();
        nuevaV.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarPacienteMouseClicked

    private void btnRegresarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegresarPacienteActionPerformed

    private void btnActualizarPacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarPacienteMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnActualizarPacienteMouseClicked

    private void btnActualizarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarPacienteActionPerformed
        Connection con = null;
        try {
            con = conectarBD.getConnection();
            conectarBD.ps = con.prepareStatement("UPDATE consultorio SET Id_Consultorio=? WHERE Id_Doctor=?");
            conectarBD.ps.setString(1, txtId_ConsultorioA.getText());
            conectarBD.ps.setString(2, txtId_DoctorConsultorioA.getText());
        

            //EJECUTAR LA CONSULTA
            int res = conectarBD.ps.executeUpdate();
            if(res > 0){
                JOptionPane.showMessageDialog(null, "CONSULTORIO ACTUALIZADO");
                limpiarCajas();
            }else{
                JOptionPane.showMessageDialog(null, "ERROR AL ACTUALIZAR CONSULTORIO");
                limpiarCajas();
            }
            //CERRAR BD
            con.close();
        } catch (Exception e) {
            System.out.println("Error: "+e); //TODOS CAMBIAR
        }
    }//GEN-LAST:event_btnActualizarPacienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Actualizar_ConsultorioR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Actualizar_ConsultorioR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Actualizar_ConsultorioR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Actualizar_ConsultorioR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Actualizar_ConsultorioR().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Cuerpo;
    private javax.swing.JPanel Encabezado;
    private javax.swing.JLabel EncabezadoActualizar_Consultorio;
    private javax.swing.JLabel Id_Consultorio;
    private javax.swing.JLabel Id_Doctor;
    private javax.swing.JButton btnActualizarPaciente;
    private javax.swing.JButton btnBuscarConsultorio;
    private javax.swing.JButton btnRegresarPaciente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtId_ConsultorioA;
    private javax.swing.JTextField txtId_DoctorConsultorioA;
    // End of variables declaration//GEN-END:variables
}
