/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;

import Clases.Conectar;
import java.sql.Connection;
import javax.swing.JOptionPane;
/**
 *
 * @author rafae
 */
public class Actualizar_DoctorD extends javax.swing.JFrame {
    Conectar conectarBD = new Conectar();
    /**
     * Creates new form Actualizar_DoctorD
     */
    public Actualizar_DoctorD() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Encabezado = new javax.swing.JPanel();
        Nombre_Encabezado = new javax.swing.JLabel();
        Cuerpo = new javax.swing.JPanel();
        Nombre_Paciente = new javax.swing.JLabel();
        Apellido_Paterno = new javax.swing.JLabel();
        Apellido_Materno = new javax.swing.JLabel();
        CURP = new javax.swing.JLabel();
        Telefono = new javax.swing.JLabel();
        txtApellidoPaternoDoctorA = new javax.swing.JTextField();
        txtApellidoMaternoDoctorA = new javax.swing.JTextField();
        txtId_DoctorA = new javax.swing.JTextField();
        txtEspecialidadA = new javax.swing.JTextField();
        btnActualizarDoctor = new javax.swing.JButton();
        txtNombreDoctorA = new javax.swing.JTextField();
        btnRegresarDoctor = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnBuscarDoctor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Encabezado.setBackground(new java.awt.Color(0, 153, 255));

        Nombre_Encabezado.setFont(new java.awt.Font("Segoe UI Black", 0, 20)); // NOI18N
        Nombre_Encabezado.setForeground(new java.awt.Color(255, 255, 255));
        Nombre_Encabezado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Nombre_Encabezado.setText("ACTUALIZAR DOCTOR");

        javax.swing.GroupLayout EncabezadoLayout = new javax.swing.GroupLayout(Encabezado);
        Encabezado.setLayout(EncabezadoLayout);
        EncabezadoLayout.setHorizontalGroup(
            EncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EncabezadoLayout.createSequentialGroup()
                .addContainerGap(257, Short.MAX_VALUE)
                .addComponent(Nombre_Encabezado)
                .addGap(211, 211, 211))
        );
        EncabezadoLayout.setVerticalGroup(
            EncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EncabezadoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Nombre_Encabezado, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        jPanel1.add(Encabezado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 60));

        Cuerpo.setBackground(new java.awt.Color(153, 204, 255));

        Nombre_Paciente.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        Nombre_Paciente.setForeground(new java.awt.Color(0, 51, 51));
        Nombre_Paciente.setText("NOMBRE DEL DOCTOR");

        Apellido_Paterno.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        Apellido_Paterno.setForeground(new java.awt.Color(0, 51, 51));
        Apellido_Paterno.setText("APELLIDO PATERNO");

        Apellido_Materno.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        Apellido_Materno.setForeground(new java.awt.Color(0, 51, 51));
        Apellido_Materno.setText("APELLIDO MATERNO");

        CURP.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        CURP.setForeground(new java.awt.Color(0, 51, 51));
        CURP.setText("ID DOCTOR (10)");

        Telefono.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        Telefono.setForeground(new java.awt.Color(0, 51, 51));
        Telefono.setText("ESPECIALIDAD");

        txtApellidoPaternoDoctorA.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtApellidoPaternoDoctorA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoPaternoDoctorAActionPerformed(evt);
            }
        });

        txtApellidoMaternoDoctorA.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtId_DoctorA.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtId_DoctorA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtId_DoctorAActionPerformed(evt);
            }
        });

        txtEspecialidadA.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnActualizarDoctor.setBackground(new java.awt.Color(0, 153, 255));
        btnActualizarDoctor.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnActualizarDoctor.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizarDoctor.setText("ACTUALIZAR");
        btnActualizarDoctor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnActualizarDoctorMouseClicked(evt);
            }
        });
        btnActualizarDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarDoctorActionPerformed(evt);
            }
        });

        txtNombreDoctorA.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtNombreDoctorA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreDoctorAActionPerformed(evt);
            }
        });

        btnRegresarDoctor.setBackground(new java.awt.Color(0, 153, 255));
        btnRegresarDoctor.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnRegresarDoctor.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresarDoctor.setText("REGRESAR");
        btnRegresarDoctor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegresarDoctorMouseClicked(evt);
            }
        });
        btnRegresarDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarDoctorActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 153));
        jLabel1.setText("BUSCAR DOCTOR:");

        btnBuscarDoctor.setBackground(new java.awt.Color(0, 153, 255));
        btnBuscarDoctor.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnBuscarDoctor.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarDoctor.setText("BUSCAR");
        btnBuscarDoctor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarDoctorMouseClicked(evt);
            }
        });
        btnBuscarDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarDoctorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CuerpoLayout = new javax.swing.GroupLayout(Cuerpo);
        Cuerpo.setLayout(CuerpoLayout);
        CuerpoLayout.setHorizontalGroup(
            CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CuerpoLayout.createSequentialGroup()
                .addGroup(CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CuerpoLayout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Apellido_Paterno)
                                .addComponent(Nombre_Paciente)
                                .addComponent(Apellido_Materno)
                                .addComponent(Telefono))
                            .addComponent(btnActualizarDoctor))
                        .addGroup(CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CuerpoLayout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(btnRegresarDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(CuerpoLayout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addGroup(CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNombreDoctorA, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                                    .addComponent(txtApellidoPaternoDoctorA)
                                    .addComponent(txtApellidoMaternoDoctorA)
                                    .addComponent(txtEspecialidadA)))))
                    .addGroup(CuerpoLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(CURP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtId_DoctorA, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscarDoctor)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        CuerpoLayout.setVerticalGroup(
            CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CuerpoLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(CURP)
                    .addComponent(txtId_DoctorA, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarDoctor))
                .addGap(41, 41, 41)
                .addGroup(CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Nombre_Paciente)
                    .addComponent(txtNombreDoctorA, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Apellido_Paterno)
                    .addComponent(txtApellidoPaternoDoctorA, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Apellido_Materno)
                    .addComponent(txtApellidoMaternoDoctorA, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Telefono)
                    .addComponent(txtEspecialidadA, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegresarDoctor)
                    .addComponent(btnActualizarDoctor))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        jPanel1.add(Cuerpo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 690, 350));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void limpiarCajas(){
        txtId_DoctorA.setText(null);
        txtNombreDoctorA.setText(null);
        txtApellidoPaternoDoctorA.setText(null);
        txtApellidoMaternoDoctorA.setText(null);
        txtEspecialidadA.setText(null);
    }
    
    private void txtApellidoPaternoDoctorAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoPaternoDoctorAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoPaternoDoctorAActionPerformed

    private void txtId_DoctorAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtId_DoctorAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtId_DoctorAActionPerformed

    private void btnActualizarDoctorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarDoctorMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnActualizarDoctorMouseClicked

    private void btnActualizarDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarDoctorActionPerformed
        Connection con = null;
        try {
            con = conectarBD.getConnection();
            conectarBD.ps = con.prepareStatement("UPDATE doctor SET Nombre_Doctor=?, Apellido_Paterno_Doctor=?, Apellido_Materno_Doctor=?, Especialidad=? WHERE Id_Doctor=?");
            conectarBD.ps.setString(1, txtNombreDoctorA.getText());
            conectarBD.ps.setString(2, txtApellidoPaternoDoctorA.getText());
            conectarBD.ps.setString(3, txtApellidoMaternoDoctorA.getText());
            conectarBD.ps.setString(4, txtEspecialidadA.getText());
            conectarBD.ps.setString(5, txtId_DoctorA.getText());

            //EJECUTAR LA CONSULTA
            int res = conectarBD.ps.executeUpdate();
            if(res > 0){
                JOptionPane.showMessageDialog(null, "DOCTOR ACTUALIZADO");
                limpiarCajas();
            }else{
                JOptionPane.showMessageDialog(null, "ERROR AL ACTUALIZAR DOCTOR");
                limpiarCajas();
            }
            //CERRAR BD
            con.close();
        } catch (Exception e) {
            System.err.println("Error: "+e);
        }
    }//GEN-LAST:event_btnActualizarDoctorActionPerformed

    private void txtNombreDoctorAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreDoctorAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreDoctorAActionPerformed

    private void btnRegresarDoctorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarDoctorMouseClicked
        PrincipalRecepcionista nuevaV = new PrincipalRecepcionista();
        nuevaV.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarDoctorMouseClicked

    private void btnRegresarDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarDoctorActionPerformed
        Principal_Doctor nuevaV = new Principal_Doctor();
        nuevaV.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarDoctorActionPerformed

    private void btnBuscarDoctorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarDoctorMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarDoctorMouseClicked

    private void btnBuscarDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarDoctorActionPerformed
        Connection con = null;
        try {
            con = conectarBD.getConnection();
            conectarBD.ps = con.prepareStatement("SELECT * FROM doctor WHERE Id_Doctor = ?");
            conectarBD.ps.setString(1, txtId_DoctorA.getText());

            conectarBD.rs = conectarBD.ps.executeQuery(); //TRAER LOS RESULTADOS DE LA CONSULTA
            if(conectarBD.rs.next()){
                txtNombreDoctorA.setText(conectarBD.rs.getString("Nombre_Doctor"));
                txtApellidoPaternoDoctorA.setText(conectarBD.rs.getString("Apellido_Paterno_Doctor"));
                txtApellidoMaternoDoctorA.setText(conectarBD.rs.getString("Apellido_Materno_Doctor"));
                txtEspecialidadA.setText(conectarBD.rs.getString("Especialidad"));
            }else{
                JOptionPane.showMessageDialog(null, "NO SE ENCONTRARON RESULTADOS");
            }
            //EJECUTAR LA CONSULTA
            int res = conectarBD.ps.executeUpdate();
            if(res > 0){
                JOptionPane.showMessageDialog(null, "DOCTOR ACTUALIZADO");
                limpiarCajas();
            }
            else{
                JOptionPane.showMessageDialog(null, "VERIFICA LA CLAVE DEL DOCTOR");
                limpiarCajas();
            }
            //CERRAR BD
            con.close();
        } catch (Exception e) {
            System.err.println("Error: "+e);
        }
    }//GEN-LAST:event_btnBuscarDoctorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Actualizar_DoctorD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Actualizar_DoctorD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Actualizar_DoctorD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Actualizar_DoctorD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Actualizar_DoctorD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Apellido_Materno;
    private javax.swing.JLabel Apellido_Paterno;
    private javax.swing.JLabel CURP;
    private javax.swing.JPanel Cuerpo;
    private javax.swing.JPanel Encabezado;
    private javax.swing.JLabel Nombre_Encabezado;
    private javax.swing.JLabel Nombre_Paciente;
    private javax.swing.JLabel Telefono;
    private javax.swing.JButton btnActualizarDoctor;
    private javax.swing.JButton btnBuscarDoctor;
    private javax.swing.JButton btnRegresarDoctor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtApellidoMaternoDoctorA;
    private javax.swing.JTextField txtApellidoPaternoDoctorA;
    private javax.swing.JTextField txtEspecialidadA;
    private javax.swing.JTextField txtId_DoctorA;
    private javax.swing.JTextField txtNombreDoctorA;
    // End of variables declaration//GEN-END:variables
}
