/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;

import Clases.Conectar;
import java.sql.Connection;
import java.sql.Time;
import javax.swing.JOptionPane;

/**
 *
 * @author rafael
 */
public class Actualizar_PacienteR extends javax.swing.JFrame {
    Conectar conectarBD = new Conectar();
    

    /**
     * Creates new form Actualizar_PacienteN
     */
    public Actualizar_PacienteR() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Encabezado = new javax.swing.JPanel();
        Nombre_Encabezado = new javax.swing.JLabel();
        Cuerpo = new javax.swing.JPanel();
        Nombre_Paciente = new javax.swing.JLabel();
        Apellido_Paterno = new javax.swing.JLabel();
        Apellido_Materno = new javax.swing.JLabel();
        CURP = new javax.swing.JLabel();
        Telefono = new javax.swing.JLabel();
        Hora_Entrada = new javax.swing.JLabel();
        Hora_Salida = new javax.swing.JLabel();
        txtApellidoPaternoPacienteA = new javax.swing.JTextField();
        txtApellidoMaternoPacienteA = new javax.swing.JTextField();
        txtCurpPacienteA = new javax.swing.JTextField();
        txtTelefonoPacienteA = new javax.swing.JTextField();
        txtHoraEntradaPacienteA = new javax.swing.JTextField();
        txtHoraSalidaPacienteA = new javax.swing.JTextField();
        btnActualizarPaciente = new javax.swing.JButton();
        txtNombrePacienteA = new javax.swing.JTextField();
        btnRegresarPaciente = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnBuscarPaciente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Encabezado.setBackground(new java.awt.Color(0, 153, 255));

        Nombre_Encabezado.setFont(new java.awt.Font("Segoe UI Black", 0, 20)); // NOI18N
        Nombre_Encabezado.setForeground(new java.awt.Color(255, 255, 255));
        Nombre_Encabezado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Nombre_Encabezado.setText("ACTUALIZAR PACIENTES");

        javax.swing.GroupLayout EncabezadoLayout = new javax.swing.GroupLayout(Encabezado);
        Encabezado.setLayout(EncabezadoLayout);
        EncabezadoLayout.setHorizontalGroup(
            EncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EncabezadoLayout.createSequentialGroup()
                .addContainerGap(232, Short.MAX_VALUE)
                .addComponent(Nombre_Encabezado)
                .addGap(211, 211, 211))
        );
        EncabezadoLayout.setVerticalGroup(
            EncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EncabezadoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Nombre_Encabezado, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        jPanel1.add(Encabezado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 60));

        Cuerpo.setBackground(new java.awt.Color(153, 204, 255));

        Nombre_Paciente.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        Nombre_Paciente.setForeground(new java.awt.Color(0, 51, 51));
        Nombre_Paciente.setText("NOMBRE DEL PACIENTE");

        Apellido_Paterno.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        Apellido_Paterno.setForeground(new java.awt.Color(0, 51, 51));
        Apellido_Paterno.setText("APELLIDO PATERNO");

        Apellido_Materno.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        Apellido_Materno.setForeground(new java.awt.Color(0, 51, 51));
        Apellido_Materno.setText("APELLIDO MATERNO");

        CURP.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        CURP.setForeground(new java.awt.Color(0, 51, 51));
        CURP.setText("CURP");

        Telefono.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        Telefono.setForeground(new java.awt.Color(0, 51, 51));
        Telefono.setText("TELÉFONO");

        Hora_Entrada.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        Hora_Entrada.setForeground(new java.awt.Color(0, 51, 51));
        Hora_Entrada.setText("HORA DE ENTRADA");

        Hora_Salida.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        Hora_Salida.setForeground(new java.awt.Color(0, 51, 51));
        Hora_Salida.setText("HORA DE SALIDA");

        txtApellidoPaternoPacienteA.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtApellidoPaternoPacienteA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoPaternoPacienteAActionPerformed(evt);
            }
        });

        txtApellidoMaternoPacienteA.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtCurpPacienteA.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtCurpPacienteA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCurpPacienteAActionPerformed(evt);
            }
        });

        txtTelefonoPacienteA.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtHoraEntradaPacienteA.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtHoraSalidaPacienteA.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnActualizarPaciente.setBackground(new java.awt.Color(0, 153, 255));
        btnActualizarPaciente.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnActualizarPaciente.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizarPaciente.setText("ACTUALIZAR");
        btnActualizarPaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnActualizarPacienteMouseClicked(evt);
            }
        });
        btnActualizarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarPacienteActionPerformed(evt);
            }
        });

        txtNombrePacienteA.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtNombrePacienteA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombrePacienteAActionPerformed(evt);
            }
        });

        btnRegresarPaciente.setBackground(new java.awt.Color(0, 153, 255));
        btnRegresarPaciente.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnRegresarPaciente.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresarPaciente.setText("REGRESAR");
        btnRegresarPaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegresarPacienteMouseClicked(evt);
            }
        });
        btnRegresarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarPacienteActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 153));
        jLabel1.setText("BUSCAR PACIENTE:");

        btnBuscarPaciente.setBackground(new java.awt.Color(0, 153, 255));
        btnBuscarPaciente.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnBuscarPaciente.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarPaciente.setText("BUSCAR");
        btnBuscarPaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarPacienteMouseClicked(evt);
            }
        });
        btnBuscarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPacienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CuerpoLayout = new javax.swing.GroupLayout(Cuerpo);
        Cuerpo.setLayout(CuerpoLayout);
        CuerpoLayout.setHorizontalGroup(
            CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CuerpoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Hora_Entrada)
                    .addComponent(Hora_Salida)
                    .addComponent(Telefono)
                    .addComponent(Apellido_Materno)
                    .addComponent(Apellido_Paterno)
                    .addComponent(Nombre_Paciente)
                    .addComponent(jLabel1))
                .addGroup(CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CuerpoLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CuerpoLayout.createSequentialGroup()
                                .addGroup(CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtHoraSalidaPacienteA, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                    .addComponent(txtHoraEntradaPacienteA, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnActualizarPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnRegresarPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(33, 33, 33))
                            .addGroup(CuerpoLayout.createSequentialGroup()
                                .addGroup(CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNombrePacienteA, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtApellidoPaternoPacienteA, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtApellidoMaternoPacienteA, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTelefonoPacienteA, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(CuerpoLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(CURP)
                        .addGap(18, 18, 18)
                        .addComponent(txtCurpPacienteA, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscarPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18))))
        );
        CuerpoLayout.setVerticalGroup(
            CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CuerpoLayout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addGroup(CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CuerpoLayout.createSequentialGroup()
                        .addGroup(CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CURP)
                            .addComponent(jLabel1)
                            .addComponent(txtCurpPacienteA, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscarPaciente))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Nombre_Paciente)
                            .addComponent(txtNombrePacienteA, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtApellidoPaternoPacienteA, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Apellido_Paterno))
                        .addGap(18, 18, 18)
                        .addGroup(CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Apellido_Materno, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtApellidoMaternoPacienteA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Telefono)
                            .addComponent(txtTelefonoPacienteA, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Hora_Entrada)
                            .addComponent(txtHoraEntradaPacienteA, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Hora_Salida)
                            .addComponent(txtHoraSalidaPacienteA, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29))
                    .addGroup(CuerpoLayout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(btnRegresarPaciente)
                        .addGap(30, 30, 30)
                        .addComponent(btnActualizarPaciente)
                        .addGap(16, 22, Short.MAX_VALUE))))
        );

        jPanel1.add(Cuerpo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 690, 390));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void limpiarCajas(){
        txtNombrePacienteA.setText(null);
        txtApellidoPaternoPacienteA.setText(null);
        txtApellidoMaternoPacienteA.setText(null);
        txtCurpPacienteA.setText(null);
        txtTelefonoPacienteA.setText(null);
        txtHoraEntradaPacienteA.setText(null);
        txtHoraSalidaPacienteA.setText(null);
    }
    
    private void txtApellidoPaternoPacienteAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoPaternoPacienteAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoPaternoPacienteAActionPerformed

    private void txtCurpPacienteAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCurpPacienteAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCurpPacienteAActionPerformed

    private void btnActualizarPacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarPacienteMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnActualizarPacienteMouseClicked

    private void btnActualizarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarPacienteActionPerformed
        Connection con = null;
        try {
            con = conectarBD.getConnection();
            conectarBD.ps = con.prepareStatement("UPDATE paciente SET Nombre_Paciente=?, Apellido_Paterno_Paciente=?, Apellido_Materno_Paciente=?, Telefono=?, Hora_Entrada=?, Hora_Salida=? WHERE CURP=?");
            conectarBD.ps.setString(1, txtNombrePacienteA.getText());
            conectarBD.ps.setString(2, txtApellidoPaternoPacienteA.getText());
            conectarBD.ps.setString(3, txtApellidoMaternoPacienteA.getText());
            conectarBD.ps.setString(4, txtTelefonoPacienteA.getText());
            conectarBD.ps.setTime(5,Time.valueOf(txtHoraEntradaPacienteA.getText()));
            conectarBD.ps.setTime(6,Time.valueOf(txtHoraSalidaPacienteA.getText()));
            conectarBD.ps.setString(7, txtCurpPacienteA.getText());
            
            //EJECUTAR LA CONSULTA
            int res = conectarBD.ps.executeUpdate();
            if(res > 0){
                JOptionPane.showMessageDialog(null, "PACIENTE ACTUALIZADO");
                limpiarCajas();
            }else{
                JOptionPane.showMessageDialog(null, "ERROR AL ACTUALIZAR PACIENTE");
                limpiarCajas();
            }
            //CERRAR BD
            con.close();
        } catch (Exception e) {
            System.err.println("Error: "+e);
        }   
    }//GEN-LAST:event_btnActualizarPacienteActionPerformed

    private void txtNombrePacienteAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombrePacienteAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombrePacienteAActionPerformed

    private void btnRegresarPacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarPacienteMouseClicked
        PrincipalRecepcionista nuevaV = new PrincipalRecepcionista();
        nuevaV.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarPacienteMouseClicked

    private void btnRegresarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegresarPacienteActionPerformed

    private void btnBuscarPacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarPacienteMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarPacienteMouseClicked

    private void btnBuscarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPacienteActionPerformed
        Connection con = null;
        try {
            con = conectarBD.getConnection();
            conectarBD.ps = con.prepareStatement("SELECT * FROM paciente WHERE CURP = ?");
            conectarBD.ps.setString(1, txtCurpPacienteA.getText());
            
            conectarBD.rs = conectarBD.ps.executeQuery(); //TRAER LOS RESULTADOS DE LA CONSULTA
            if(conectarBD.rs.next()){
                txtNombrePacienteA.setText(conectarBD.rs.getString("Nombre_Paciente"));
                txtApellidoPaternoPacienteA.setText(conectarBD.rs.getString("Apellido_Paterno_Paciente"));
                txtApellidoMaternoPacienteA.setText(conectarBD.rs.getString("Apellido_Materno_Paciente"));
                txtTelefonoPacienteA.setText(conectarBD.rs.getString("Telefono"));
                txtHoraEntradaPacienteA.setText(conectarBD.rs.getString("Hora_Entrada"));
                txtHoraSalidaPacienteA.setText(conectarBD.rs.getString("Hora_Salida"));
            }else{
                JOptionPane.showMessageDialog(null, "NO SE ENCONTRARON RESULTADOS");
            }
            //EJECUTAR LA CONSULTA
            int res = conectarBD.ps.executeUpdate();
            if(res > 0){
                JOptionPane.showMessageDialog(null, "PACIENTE ACTUALIZADO");
                limpiarCajas();
            }
            else{
                JOptionPane.showMessageDialog(null, "ERROR AL ACTUALIZAR PACIENTE");
                limpiarCajas();
            }
            //CERRAR BD
            con.close();
        } catch (Exception e) {
            System.err.println("Error: "+e);
        }
    }//GEN-LAST:event_btnBuscarPacienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Actualizar_PacienteR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Actualizar_PacienteR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Actualizar_PacienteR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Actualizar_PacienteR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Actualizar_PacienteR().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Apellido_Materno;
    private javax.swing.JLabel Apellido_Paterno;
    private javax.swing.JLabel CURP;
    private javax.swing.JPanel Cuerpo;
    private javax.swing.JPanel Encabezado;
    private javax.swing.JLabel Hora_Entrada;
    private javax.swing.JLabel Hora_Salida;
    private javax.swing.JLabel Nombre_Encabezado;
    private javax.swing.JLabel Nombre_Paciente;
    private javax.swing.JLabel Telefono;
    private javax.swing.JButton btnActualizarPaciente;
    private javax.swing.JButton btnBuscarPaciente;
    private javax.swing.JButton btnRegresarPaciente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtApellidoMaternoPacienteA;
    private javax.swing.JTextField txtApellidoPaternoPacienteA;
    private javax.swing.JTextField txtCurpPacienteA;
    private javax.swing.JTextField txtHoraEntradaPacienteA;
    private javax.swing.JTextField txtHoraSalidaPacienteA;
    private javax.swing.JTextField txtNombrePacienteA;
    private javax.swing.JTextField txtTelefonoPacienteA;
    // End of variables declaration//GEN-END:variables
}
