/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;
import Clases.Conectar;
import java.sql.Connection;
import java.sql.Time;
import javax.swing.JOptionPane;
/**
 *
 * @author sandybau
 */
public class Actualizar_HorarioAdmin extends javax.swing.JFrame {
    Conectar conectarBD = new Conectar();

    /**
     * Creates new form Actualizar_HorarioAdmin
     */
    public Actualizar_HorarioAdmin() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Encabezado = new javax.swing.JPanel();
        Nombre_Encabezado = new javax.swing.JLabel();
        Cuerpo = new javax.swing.JPanel();
        CitaHorarioA = new javax.swing.JLabel();
        IdDoctorA = new javax.swing.JLabel();
        CURP = new javax.swing.JLabel();
        txtIdDoctorHorarioA = new javax.swing.JTextField();
        txtCurpHorarioA = new javax.swing.JTextField();
        txtCitaHorarioA = new javax.swing.JTextField();
        btnActualizarHorarioA = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnBuscarHorario = new javax.swing.JButton();
        btnRegresarHorarioA1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Encabezado.setBackground(new java.awt.Color(0, 153, 255));

        Nombre_Encabezado.setFont(new java.awt.Font("Segoe UI Black", 0, 20)); // NOI18N
        Nombre_Encabezado.setForeground(new java.awt.Color(255, 255, 255));
        Nombre_Encabezado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Nombre_Encabezado.setText("ACTUALIZAR HORARIO");

        javax.swing.GroupLayout EncabezadoLayout = new javax.swing.GroupLayout(Encabezado);
        Encabezado.setLayout(EncabezadoLayout);
        EncabezadoLayout.setHorizontalGroup(
            EncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EncabezadoLayout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addComponent(Nombre_Encabezado)
                .addContainerGap(235, Short.MAX_VALUE))
        );
        EncabezadoLayout.setVerticalGroup(
            EncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EncabezadoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Nombre_Encabezado, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        jPanel1.add(Encabezado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 60));

        Cuerpo.setBackground(new java.awt.Color(153, 204, 255));

        CitaHorarioA.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        CitaHorarioA.setForeground(new java.awt.Color(0, 51, 51));
        CitaHorarioA.setText("CITA HORARIO (MATUTINO, VESPERTINO)");

        IdDoctorA.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        IdDoctorA.setForeground(new java.awt.Color(0, 51, 51));
        IdDoctorA.setText("ID DOCTOR (10 DÍGITOS)");

        CURP.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        CURP.setForeground(new java.awt.Color(0, 51, 51));
        CURP.setText("CURP");

        txtIdDoctorHorarioA.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtIdDoctorHorarioA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdDoctorHorarioAActionPerformed(evt);
            }
        });

        txtCurpHorarioA.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtCurpHorarioA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCurpHorarioAActionPerformed(evt);
            }
        });

        txtCitaHorarioA.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtCitaHorarioA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCitaHorarioAActionPerformed(evt);
            }
        });

        btnActualizarHorarioA.setBackground(new java.awt.Color(0, 153, 255));
        btnActualizarHorarioA.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnActualizarHorarioA.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizarHorarioA.setText("ACTUALIZAR");
        btnActualizarHorarioA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnActualizarHorarioAMouseClicked(evt);
            }
        });
        btnActualizarHorarioA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarHorarioAActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 153));
        jLabel1.setText("BUSCAR HORARIO:");

        btnBuscarHorario.setBackground(new java.awt.Color(0, 153, 255));
        btnBuscarHorario.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnBuscarHorario.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarHorario.setText("BUSCAR");
        btnBuscarHorario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarHorarioMouseClicked(evt);
            }
        });
        btnBuscarHorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarHorarioActionPerformed(evt);
            }
        });

        btnRegresarHorarioA1.setBackground(new java.awt.Color(0, 153, 255));
        btnRegresarHorarioA1.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnRegresarHorarioA1.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresarHorarioA1.setText("REGRESAR");
        btnRegresarHorarioA1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegresarHorarioA1MouseClicked(evt);
            }
        });
        btnRegresarHorarioA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarHorarioA1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CuerpoLayout = new javax.swing.GroupLayout(Cuerpo);
        Cuerpo.setLayout(CuerpoLayout);
        CuerpoLayout.setHorizontalGroup(
            CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CuerpoLayout.createSequentialGroup()
                .addGroup(CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CuerpoLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CuerpoLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(CURP)
                                .addGap(18, 18, 18)
                                .addComponent(txtCurpHorarioA, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnBuscarHorario))
                            .addGroup(CuerpoLayout.createSequentialGroup()
                                .addGroup(CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CitaHorarioA)
                                    .addGroup(CuerpoLayout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(IdDoctorA)))
                                .addGap(18, 18, 18)
                                .addGroup(CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtIdDoctorHorarioA, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCitaHorarioA, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(CuerpoLayout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(btnActualizarHorarioA, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CuerpoLayout.createSequentialGroup()
                    .addContainerGap(331, Short.MAX_VALUE)
                    .addComponent(btnRegresarHorarioA1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(186, 186, 186)))
        );
        CuerpoLayout.setVerticalGroup(
            CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CuerpoLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(CURP)
                    .addComponent(txtCurpHorarioA, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarHorario))
                .addGap(30, 30, 30)
                .addGroup(CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CitaHorarioA)
                    .addComponent(txtCitaHorarioA, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IdDoctorA)
                    .addComponent(txtIdDoctorHorarioA, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(btnActualizarHorarioA)
                .addGap(40, 40, 40))
            .addGroup(CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CuerpoLayout.createSequentialGroup()
                    .addContainerGap(203, Short.MAX_VALUE)
                    .addComponent(btnRegresarHorarioA1)
                    .addGap(38, 38, 38)))
        );

        jPanel1.add(Cuerpo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 640, 270));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void limpiarCajas(){
        txtCurpHorarioA.setText(null);
        txtCitaHorarioA.setText(null);
        txtIdDoctorHorarioA.setText(null);
    }
    private void txtIdDoctorHorarioAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdDoctorHorarioAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdDoctorHorarioAActionPerformed

    private void txtCurpHorarioAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCurpHorarioAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCurpHorarioAActionPerformed

    private void txtCitaHorarioAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCitaHorarioAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCitaHorarioAActionPerformed

    private void btnActualizarHorarioAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarHorarioAMouseClicked
        
    }//GEN-LAST:event_btnActualizarHorarioAMouseClicked

    private void btnActualizarHorarioAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarHorarioAActionPerformed
        Connection con = null;
        try {
            con = conectarBD.getConnection();
            conectarBD.ps = con.prepareStatement("UPDATE horario SET Cita_Horario=?, Id_Doctor=? WHERE CURP=?");
            conectarBD.ps.setString(1, txtCitaHorarioA.getText());
            conectarBD.ps.setString(2, txtIdDoctorHorarioA.getText());
            conectarBD.ps.setString(3, txtCurpHorarioA.getText());

            //EJECUTAR LA CONSULTA
            int res = conectarBD.ps.executeUpdate();
            if(res > 0){
                JOptionPane.showMessageDialog(null, "HORARIO ACTUALIZADO");
                limpiarCajas();
            }else{
                JOptionPane.showMessageDialog(null, "ERROR AL ACTUALIZAR HORARIO");
                limpiarCajas();
            }
            //CERRAR BD
            con.close();
        } catch (Exception e) {
            System.err.println("Error: "+e);
        }
    }//GEN-LAST:event_btnActualizarHorarioAActionPerformed

    private void btnBuscarHorarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarHorarioMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarHorarioMouseClicked

    private void btnBuscarHorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarHorarioActionPerformed
        Connection con = null;
        try {
            con = conectarBD.getConnection();
            conectarBD.ps = con.prepareStatement("SELECT * FROM horario WHERE CURP = ?");
            conectarBD.ps.setString(1, txtCurpHorarioA.getText());

            conectarBD.rs = conectarBD.ps.executeQuery(); //TRAER LOS RESULTADOS DE LA CONSULTA
            if(conectarBD.rs.next()){
                txtCitaHorarioA.setText(conectarBD.rs.getString("Cita_Horario"));
                txtIdDoctorHorarioA.setText(conectarBD.rs.getString("Id_Doctor"));
            }else{
                JOptionPane.showMessageDialog(null, "NO SE ENCONTRARON RESULTADOS");
            }
            //EJECUTAR LA CONSULTA
            int res = conectarBD.ps.executeUpdate();
            if(res > 0){
                JOptionPane.showMessageDialog(null, "HORARIO ACTUALIZADO");
                limpiarCajas();
            }
            else{
                JOptionPane.showMessageDialog(null, "VERIFICA LA CLAVE DEL HORARIO");
                limpiarCajas();
            }
            //CERRAR BD
            con.close();
        } catch (Exception e) {
            System.err.println("Error: "+e);
        }
    }//GEN-LAST:event_btnBuscarHorarioActionPerformed

    private void btnRegresarHorarioA1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarHorarioA1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegresarHorarioA1MouseClicked

    private void btnRegresarHorarioA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarHorarioA1ActionPerformed
        Principal_Administrador nuevaV = new Principal_Administrador();
        nuevaV.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarHorarioA1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Actualizar_HorarioAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Actualizar_HorarioAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Actualizar_HorarioAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Actualizar_HorarioAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Actualizar_HorarioAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CURP;
    private javax.swing.JLabel CitaHorarioA;
    private javax.swing.JPanel Cuerpo;
    private javax.swing.JPanel Encabezado;
    private javax.swing.JLabel IdDoctorA;
    private javax.swing.JLabel Nombre_Encabezado;
    private javax.swing.JButton btnActualizarHorarioA;
    private javax.swing.JButton btnBuscarHorario;
    private javax.swing.JButton btnRegresarHorarioA1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtCitaHorarioA;
    private javax.swing.JTextField txtCurpHorarioA;
    private javax.swing.JTextField txtIdDoctorHorarioA;
    // End of variables declaration//GEN-END:variables
}
