/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;

import Clases.Conectar;
import java.sql.Connection;
import javax.swing.JOptionPane;
/**
 *
 * @author sandybau
 */
public class Consultar_ConsultorioR extends javax.swing.JFrame {
    Conectar conectarBD = new Conectar();
    /**
     * Creates new form Consultar_Consultorio
     */
    public Consultar_ConsultorioR() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Encabezado = new javax.swing.JPanel();
        EncabezadoActualizar_Consultorio = new javax.swing.JLabel();
        Cuerpo = new javax.swing.JPanel();
        Id_ConsultorioC = new javax.swing.JLabel();
        labelId_DoctorConsulta = new javax.swing.JLabel();
        txtId_DoctorConsultorioC = new javax.swing.JTextField();
        txtId_ConsultorioC = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnRegresarPaciente = new javax.swing.JButton();
        btnConsultarConsultorio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Encabezado.setBackground(new java.awt.Color(0, 153, 255));

        EncabezadoActualizar_Consultorio.setFont(new java.awt.Font("Segoe UI Black", 0, 20)); // NOI18N
        EncabezadoActualizar_Consultorio.setForeground(new java.awt.Color(255, 255, 255));
        EncabezadoActualizar_Consultorio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EncabezadoActualizar_Consultorio.setText("CONSULTAR CONSULTORIO");

        javax.swing.GroupLayout EncabezadoLayout = new javax.swing.GroupLayout(Encabezado);
        Encabezado.setLayout(EncabezadoLayout);
        EncabezadoLayout.setHorizontalGroup(
            EncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EncabezadoLayout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(EncabezadoActualizar_Consultorio)
                .addContainerGap(297, Short.MAX_VALUE))
        );
        EncabezadoLayout.setVerticalGroup(
            EncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EncabezadoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(EncabezadoActualizar_Consultorio, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        jPanel1.add(Encabezado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 60));

        Cuerpo.setBackground(new java.awt.Color(153, 204, 255));

        Id_ConsultorioC.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        Id_ConsultorioC.setForeground(new java.awt.Color(0, 51, 51));
        Id_ConsultorioC.setText("ID CONSULTORIO (5)");

        labelId_DoctorConsulta.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        labelId_DoctorConsulta.setForeground(new java.awt.Color(0, 51, 51));
        labelId_DoctorConsulta.setText("ID DOCTOR (10)");

        txtId_DoctorConsultorioC.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtId_DoctorConsultorioC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtId_DoctorConsultorioCActionPerformed(evt);
            }
        });

        txtId_ConsultorioC.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtId_ConsultorioC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtId_ConsultorioCActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 153));
        jLabel1.setText("BUSCAR DOCTOR:");

        btnRegresarPaciente.setBackground(new java.awt.Color(0, 153, 255));
        btnRegresarPaciente.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnRegresarPaciente.setText("REGRESAR");
        btnRegresarPaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegresarPacienteMouseClicked(evt);
            }
        });
        btnRegresarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarPacienteActionPerformed(evt);
            }
        });

        btnConsultarConsultorio.setBackground(new java.awt.Color(0, 153, 255));
        btnConsultarConsultorio.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnConsultarConsultorio.setText("BUSCAR");
        btnConsultarConsultorio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConsultarConsultorioMouseClicked(evt);
            }
        });
        btnConsultarConsultorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarConsultorioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CuerpoLayout = new javax.swing.GroupLayout(Cuerpo);
        Cuerpo.setLayout(CuerpoLayout);
        CuerpoLayout.setHorizontalGroup(
            CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CuerpoLayout.createSequentialGroup()
                .addGroup(CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CuerpoLayout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(btnConsultarConsultorio, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69)
                        .addComponent(btnRegresarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CuerpoLayout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(Id_ConsultorioC)
                        .addGap(47, 47, 47)
                        .addComponent(txtId_ConsultorioC, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CuerpoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(30, 30, 30)
                        .addComponent(labelId_DoctorConsulta)
                        .addGap(18, 18, 18)
                        .addComponent(txtId_DoctorConsultorioC, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        CuerpoLayout.setVerticalGroup(
            CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CuerpoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtId_DoctorConsultorioC, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelId_DoctorConsulta)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtId_ConsultorioC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Id_ConsultorioC, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(35, 35, 35)
                .addGroup(CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegresarPaciente)
                    .addComponent(btnConsultarConsultorio))
                .addGap(50, 50, 50))
        );

        jPanel1.add(Cuerpo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 740, 210));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void limpiarCajas(){
        txtId_DoctorConsultorioC.setText(null);
        txtId_ConsultorioC.setText(null);
    }
    private void txtId_DoctorConsultorioCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtId_DoctorConsultorioCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtId_DoctorConsultorioCActionPerformed

    private void txtId_ConsultorioCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtId_ConsultorioCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtId_ConsultorioCActionPerformed

    private void btnRegresarPacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarPacienteMouseClicked
        PrincipalRecepcionista nuevaV = new PrincipalRecepcionista();
        nuevaV.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarPacienteMouseClicked

    private void btnRegresarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegresarPacienteActionPerformed

    private void btnConsultarConsultorioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultarConsultorioMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultarConsultorioMouseClicked

    private void btnConsultarConsultorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarConsultorioActionPerformed
        Connection con = null;
        try {
            con = conectarBD.getConnection();
            conectarBD.ps = con.prepareStatement("SELECT * FROM consultorio WHERE Id_Doctor = ?");
            conectarBD.ps.setString(1, txtId_DoctorConsultorioC.getText());

            conectarBD.rs = conectarBD.ps.executeQuery(); //TRAER LOS RESULTADOS DE LA CONSULTA
            if(conectarBD.rs.next()){
                txtId_ConsultorioC.setText(conectarBD.rs.getString("Id_Consultorio"));
            }else{
                JOptionPane.showMessageDialog(null, "NO SE ENCONTRARON RESULTADOS");
            }
            //EJECUTAR LA CONSULTA
            int res = conectarBD.ps.executeUpdate();
            if(res > 0){
                JOptionPane.showMessageDialog(null, "CONSULTORIO LOCALIZADO");
                limpiarCajas();
            }
            else{
                JOptionPane.showMessageDialog(null, "ERROR AL CONSULTAR CONSULTORIO");
                limpiarCajas();
            }
            //CERRAR BD
            con.close();
        } catch (Exception e) {
            System.err.println("Error: "+e);
        }
    }//GEN-LAST:event_btnConsultarConsultorioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consultar_ConsultorioR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consultar_ConsultorioR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consultar_ConsultorioR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consultar_ConsultorioR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Consultar_ConsultorioR().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Cuerpo;
    private javax.swing.JPanel Encabezado;
    private javax.swing.JLabel EncabezadoActualizar_Consultorio;
    private javax.swing.JLabel Id_ConsultorioC;
    private javax.swing.JButton btnConsultarConsultorio;
    private javax.swing.JButton btnRegresarPaciente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelId_DoctorConsulta;
    private javax.swing.JTextField txtId_ConsultorioC;
    private javax.swing.JTextField txtId_DoctorConsultorioC;
    // End of variables declaration//GEN-END:variables
}
