/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;
import Clases.Conectar;
import java.sql.Connection;
import javax.swing.JOptionPane;
/**
 *
 * @author sandybau
 */
public class Consultar_PacienteAdmin extends javax.swing.JFrame {
    Conectar conectarBD = new Conectar();
    /**
     * Creates new form Consultar_PacienteAdmin
     */
    public Consultar_PacienteAdmin() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Encabezado_ConsultaDoc = new javax.swing.JPanel();
        EncabezadoActualizar_Consultorio = new javax.swing.JLabel();
        Cuerpo = new javax.swing.JPanel();
        Nombre_Doctor = new javax.swing.JLabel();
        labelId_Doctor_ConsultaDoc = new javax.swing.JLabel();
        txtCurp_ConsultarPaciente = new javax.swing.JTextField();
        txtApellido_Materno_Paciente = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnRegresarDoctor = new javax.swing.JButton();
        btnConsultarPaciente = new javax.swing.JButton();
        txtNombrePaciente_ConsultaPaciente = new javax.swing.JTextField();
        Apellido_Paterno_ConsultDoc = new javax.swing.JLabel();
        Apellido_Materno_ConsultDoc = new javax.swing.JLabel();
        txtApellido_Paterno_Paciente = new javax.swing.JTextField();
        Especialidad_Doctor = new javax.swing.JLabel();
        txtTelefonoConsultaPaciente = new javax.swing.JTextField();
        Especialidad_Doctor1 = new javax.swing.JLabel();
        txtHoraSalida_ConsultarPaciente = new javax.swing.JTextField();
        Especialidad_Doctor2 = new javax.swing.JLabel();
        txtHoraEntrada_ConsultaPaciente = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Encabezado_ConsultaDoc.setBackground(new java.awt.Color(0, 153, 255));

        EncabezadoActualizar_Consultorio.setFont(new java.awt.Font("Segoe UI Black", 0, 20)); // NOI18N
        EncabezadoActualizar_Consultorio.setForeground(new java.awt.Color(255, 255, 255));
        EncabezadoActualizar_Consultorio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EncabezadoActualizar_Consultorio.setText("CONSULTAR PACIENTE");

        javax.swing.GroupLayout Encabezado_ConsultaDocLayout = new javax.swing.GroupLayout(Encabezado_ConsultaDoc);
        Encabezado_ConsultaDoc.setLayout(Encabezado_ConsultaDocLayout);
        Encabezado_ConsultaDocLayout.setHorizontalGroup(
            Encabezado_ConsultaDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Encabezado_ConsultaDocLayout.createSequentialGroup()
                .addContainerGap(199, Short.MAX_VALUE)
                .addComponent(EncabezadoActualizar_Consultorio)
                .addGap(203, 203, 203))
        );
        Encabezado_ConsultaDocLayout.setVerticalGroup(
            Encabezado_ConsultaDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Encabezado_ConsultaDocLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(EncabezadoActualizar_Consultorio, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        jPanel1.add(Encabezado_ConsultaDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 60));

        Cuerpo.setBackground(new java.awt.Color(153, 204, 255));

        Nombre_Doctor.setFont(new java.awt.Font("Segoe UI Black", 1, 16)); // NOI18N
        Nombre_Doctor.setForeground(new java.awt.Color(0, 51, 51));
        Nombre_Doctor.setText("NOMBRE PACIENTE");

        labelId_Doctor_ConsultaDoc.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        labelId_Doctor_ConsultaDoc.setForeground(new java.awt.Color(0, 51, 51));
        labelId_Doctor_ConsultaDoc.setText("CURP");

        txtCurp_ConsultarPaciente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtCurp_ConsultarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCurp_ConsultarPacienteActionPerformed(evt);
            }
        });

        txtApellido_Materno_Paciente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtApellido_Materno_Paciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellido_Materno_PacienteActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 153));
        jLabel1.setText("BUSCAR PACIENTE:");

        btnRegresarDoctor.setBackground(new java.awt.Color(0, 153, 255));
        btnRegresarDoctor.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnRegresarDoctor.setText("REGRESAR");
        btnRegresarDoctor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegresarDoctorMouseClicked(evt);
            }
        });
        btnRegresarDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarDoctorActionPerformed(evt);
            }
        });

        btnConsultarPaciente.setBackground(new java.awt.Color(0, 153, 255));
        btnConsultarPaciente.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnConsultarPaciente.setText("CONSULTAR");
        btnConsultarPaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConsultarPacienteMouseClicked(evt);
            }
        });
        btnConsultarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarPacienteActionPerformed(evt);
            }
        });

        txtNombrePaciente_ConsultaPaciente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtNombrePaciente_ConsultaPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombrePaciente_ConsultaPacienteActionPerformed(evt);
            }
        });

        Apellido_Paterno_ConsultDoc.setFont(new java.awt.Font("Segoe UI Black", 1, 16)); // NOI18N
        Apellido_Paterno_ConsultDoc.setForeground(new java.awt.Color(0, 51, 51));
        Apellido_Paterno_ConsultDoc.setText("APELLIDO PATERNO");

        Apellido_Materno_ConsultDoc.setFont(new java.awt.Font("Segoe UI Black", 1, 16)); // NOI18N
        Apellido_Materno_ConsultDoc.setForeground(new java.awt.Color(0, 51, 51));
        Apellido_Materno_ConsultDoc.setText("APELLIDO MATERNO");

        txtApellido_Paterno_Paciente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtApellido_Paterno_Paciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellido_Paterno_PacienteActionPerformed(evt);
            }
        });

        Especialidad_Doctor.setFont(new java.awt.Font("Segoe UI Black", 1, 16)); // NOI18N
        Especialidad_Doctor.setForeground(new java.awt.Color(0, 51, 51));
        Especialidad_Doctor.setText("HORA DE ENTRADA");

        txtTelefonoConsultaPaciente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtTelefonoConsultaPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoConsultaPacienteActionPerformed(evt);
            }
        });

        Especialidad_Doctor1.setFont(new java.awt.Font("Segoe UI Black", 1, 16)); // NOI18N
        Especialidad_Doctor1.setForeground(new java.awt.Color(0, 51, 51));
        Especialidad_Doctor1.setText("TELÉFONO");

        txtHoraSalida_ConsultarPaciente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtHoraSalida_ConsultarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHoraSalida_ConsultarPacienteActionPerformed(evt);
            }
        });

        Especialidad_Doctor2.setFont(new java.awt.Font("Segoe UI Black", 1, 16)); // NOI18N
        Especialidad_Doctor2.setForeground(new java.awt.Color(0, 51, 51));
        Especialidad_Doctor2.setText("HORA DE SALIDA");

        txtHoraEntrada_ConsultaPaciente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtHoraEntrada_ConsultaPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHoraEntrada_ConsultaPacienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CuerpoLayout = new javax.swing.GroupLayout(Cuerpo);
        Cuerpo.setLayout(CuerpoLayout);
        CuerpoLayout.setHorizontalGroup(
            CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CuerpoLayout.createSequentialGroup()
                .addGroup(CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CuerpoLayout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(btnConsultarPaciente)
                        .addGap(61, 61, 61)
                        .addComponent(btnRegresarDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CuerpoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(30, 30, 30)
                        .addComponent(labelId_Doctor_ConsultaDoc)
                        .addGap(18, 18, 18)
                        .addComponent(txtCurp_ConsultarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(102, Short.MAX_VALUE))
            .addGroup(CuerpoLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CuerpoLayout.createSequentialGroup()
                        .addComponent(Especialidad_Doctor2, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtHoraSalida_ConsultarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CuerpoLayout.createSequentialGroup()
                        .addGroup(CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Apellido_Paterno_ConsultDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Apellido_Materno_ConsultDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Especialidad_Doctor, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Nombre_Doctor, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Especialidad_Doctor1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombrePaciente_ConsultaPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                            .addComponent(txtApellido_Paterno_Paciente)
                            .addComponent(txtApellido_Materno_Paciente)
                            .addComponent(txtTelefonoConsultaPaciente)
                            .addComponent(txtHoraEntrada_ConsultaPaciente, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(70, 70, 70))
        );
        CuerpoLayout.setVerticalGroup(
            CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CuerpoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCurp_ConsultarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelId_Doctor_ConsultaDoc)
                    .addComponent(jLabel1))
                .addGap(24, 24, 24)
                .addGroup(CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombrePaciente_ConsultaPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nombre_Doctor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Apellido_Paterno_ConsultDoc)
                    .addComponent(txtApellido_Paterno_Paciente, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Apellido_Materno_ConsultDoc)
                    .addComponent(txtApellido_Materno_Paciente, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelefonoConsultaPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Especialidad_Doctor1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Especialidad_Doctor)
                    .addComponent(txtHoraEntrada_ConsultaPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Especialidad_Doctor2)
                    .addComponent(txtHoraSalida_ConsultarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegresarDoctor)
                    .addComponent(btnConsultarPaciente))
                .addGap(50, 50, 50))
        );

        jPanel1.add(Cuerpo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 630, 400));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void limpiarCajas(){
        txtNombrePaciente_ConsultaPaciente.setText(null);
        txtApellido_Paterno_Paciente.setText(null);
        txtApellido_Materno_Paciente.setText(null);
        txtCurp_ConsultarPaciente.setText(null);
        txtTelefonoConsultaPaciente.setText(null);
        txtHoraEntrada_ConsultaPaciente.setText(null);
        txtHoraSalida_ConsultarPaciente.setText(null);
    }
    private void txtCurp_ConsultarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCurp_ConsultarPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCurp_ConsultarPacienteActionPerformed

    private void txtApellido_Materno_PacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellido_Materno_PacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellido_Materno_PacienteActionPerformed

    private void btnRegresarDoctorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarDoctorMouseClicked
        Principal_Administrador nuevaV = new Principal_Administrador();
        nuevaV.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarDoctorMouseClicked

    private void btnRegresarDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarDoctorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegresarDoctorActionPerformed

    private void btnConsultarPacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultarPacienteMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultarPacienteMouseClicked

    private void btnConsultarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarPacienteActionPerformed
        Connection con = null;
        try {
            con = conectarBD.getConnection();
            conectarBD.ps = con.prepareStatement("SELECT * FROM paciente WHERE CURP = ?");
            conectarBD.ps.setString(1, txtCurp_ConsultarPaciente.getText());

            conectarBD.rs = conectarBD.ps.executeQuery(); //TRAER LOS RESULTADOS DE LA CONSULTA
            if(conectarBD.rs.next()){
                txtNombrePaciente_ConsultaPaciente.setText(conectarBD.rs.getString("Nombre_Paciente"));
                txtApellido_Paterno_Paciente.setText(conectarBD.rs.getString("Apellido_Paterno_Paciente"));
                txtApellido_Materno_Paciente.setText(conectarBD.rs.getString("Apellido_Materno_Paciente"));
                txtTelefonoConsultaPaciente.setText(conectarBD.rs.getString("Telefono"));
                txtHoraEntrada_ConsultaPaciente.setText(conectarBD.rs.getString("Hora_Entrada"));
                txtHoraSalida_ConsultarPaciente.setText(conectarBD.rs.getString("Hora_Salida"));
            }else{
                JOptionPane.showMessageDialog(null, "NO SE ENCONTRARON RESULTADOS");
            }
            //EJECUTAR LA CONSULTA
            int res = conectarBD.ps.executeUpdate();
            if(res > 0){
                JOptionPane.showMessageDialog(null, "PACIENTE ACTUALIZADO");
                limpiarCajas();
            }
            else{
                JOptionPane.showMessageDialog(null, "ERROR AL ACTUALIZAR PACIENTE");
                limpiarCajas();
            }
            //CERRAR BD
            con.close();
        } catch (Exception e) {
            System.err.println("Error: "+e);
        }
    }//GEN-LAST:event_btnConsultarPacienteActionPerformed

    private void txtNombrePaciente_ConsultaPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombrePaciente_ConsultaPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombrePaciente_ConsultaPacienteActionPerformed

    private void txtApellido_Paterno_PacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellido_Paterno_PacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellido_Paterno_PacienteActionPerformed

    private void txtTelefonoConsultaPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoConsultaPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoConsultaPacienteActionPerformed

    private void txtHoraSalida_ConsultarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoraSalida_ConsultarPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoraSalida_ConsultarPacienteActionPerformed

    private void txtHoraEntrada_ConsultaPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoraEntrada_ConsultaPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoraEntrada_ConsultaPacienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consultar_PacienteAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consultar_PacienteAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consultar_PacienteAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consultar_PacienteAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Consultar_PacienteAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Apellido_Materno_ConsultDoc;
    private javax.swing.JLabel Apellido_Paterno_ConsultDoc;
    private javax.swing.JPanel Cuerpo;
    private javax.swing.JLabel EncabezadoActualizar_Consultorio;
    private javax.swing.JPanel Encabezado_ConsultaDoc;
    private javax.swing.JLabel Especialidad_Doctor;
    private javax.swing.JLabel Especialidad_Doctor1;
    private javax.swing.JLabel Especialidad_Doctor2;
    private javax.swing.JLabel Nombre_Doctor;
    private javax.swing.JButton btnConsultarPaciente;
    private javax.swing.JButton btnRegresarDoctor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelId_Doctor_ConsultaDoc;
    private javax.swing.JTextField txtApellido_Materno_Paciente;
    private javax.swing.JTextField txtApellido_Paterno_Paciente;
    private javax.swing.JTextField txtCurp_ConsultarPaciente;
    private javax.swing.JTextField txtHoraEntrada_ConsultaPaciente;
    private javax.swing.JTextField txtHoraSalida_ConsultarPaciente;
    private javax.swing.JTextField txtNombrePaciente_ConsultaPaciente;
    private javax.swing.JTextField txtTelefonoConsultaPaciente;
    // End of variables declaration//GEN-END:variables
}
