/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;
import Clases.Conectar;
import java.sql.Connection;
import javax.swing.JOptionPane;

/**
 *
 * @author sandybau
 */
public class Consultar_DoctorAdmin extends javax.swing.JFrame {
    Conectar conectarBD = new Conectar();
    /**
     * Creates new form Consultar_DoctorAdmin
     */
    public Consultar_DoctorAdmin() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Encabezado_ConsultaDoc = new javax.swing.JPanel();
        EncabezadoActualizar_Consultorio = new javax.swing.JLabel();
        Cuerpo = new javax.swing.JPanel();
        Nombre_Doctor = new javax.swing.JLabel();
        labelId_Doctor_ConsultaDoc = new javax.swing.JLabel();
        txtId_Doctor_ConsultarDoc = new javax.swing.JTextField();
        txtApellido_Materno_Doc = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnRegresarDoctor = new javax.swing.JButton();
        btnConsultarDoctor = new javax.swing.JButton();
        txtNombreDoctor_ConsultaDoc1 = new javax.swing.JTextField();
        Apellido_Paterno_ConsultDoc = new javax.swing.JLabel();
        Apellido_Materno_ConsultDoc = new javax.swing.JLabel();
        txtApellido_Paterno_ConsultaDoc1 = new javax.swing.JTextField();
        Especialidad_Doctor = new javax.swing.JLabel();
        txtEspecialidad_ConsultaDoc = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Encabezado_ConsultaDoc.setBackground(new java.awt.Color(0, 153, 255));

        EncabezadoActualizar_Consultorio.setFont(new java.awt.Font("Segoe UI Black", 0, 20)); // NOI18N
        EncabezadoActualizar_Consultorio.setForeground(new java.awt.Color(255, 255, 255));
        EncabezadoActualizar_Consultorio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EncabezadoActualizar_Consultorio.setText("CONSULTAR DOCTOR");

        javax.swing.GroupLayout Encabezado_ConsultaDocLayout = new javax.swing.GroupLayout(Encabezado_ConsultaDoc);
        Encabezado_ConsultaDoc.setLayout(Encabezado_ConsultaDocLayout);
        Encabezado_ConsultaDocLayout.setHorizontalGroup(
            Encabezado_ConsultaDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Encabezado_ConsultaDocLayout.createSequentialGroup()
                .addContainerGap(213, Short.MAX_VALUE)
                .addComponent(EncabezadoActualizar_Consultorio)
                .addGap(203, 203, 203))
        );
        Encabezado_ConsultaDocLayout.setVerticalGroup(
            Encabezado_ConsultaDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Encabezado_ConsultaDocLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(EncabezadoActualizar_Consultorio, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        jPanel1.add(Encabezado_ConsultaDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 60));

        Cuerpo.setBackground(new java.awt.Color(153, 204, 255));

        Nombre_Doctor.setFont(new java.awt.Font("Segoe UI Black", 1, 16)); // NOI18N
        Nombre_Doctor.setForeground(new java.awt.Color(0, 51, 51));
        Nombre_Doctor.setText("NOMBRE DOCTOR");

        labelId_Doctor_ConsultaDoc.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        labelId_Doctor_ConsultaDoc.setForeground(new java.awt.Color(0, 51, 51));
        labelId_Doctor_ConsultaDoc.setText("ID DOCTOR (10)");

        txtId_Doctor_ConsultarDoc.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtId_Doctor_ConsultarDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtId_Doctor_ConsultarDocActionPerformed(evt);
            }
        });

        txtApellido_Materno_Doc.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtApellido_Materno_Doc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellido_Materno_DocActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 153));
        jLabel1.setText("Buscar Doctor:");

        btnRegresarDoctor.setBackground(new java.awt.Color(0, 153, 255));
        btnRegresarDoctor.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnRegresarDoctor.setText("REGRESAR");
        btnRegresarDoctor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegresarDoctorMouseClicked(evt);
            }
        });
        btnRegresarDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarDoctorActionPerformed(evt);
            }
        });

        btnConsultarDoctor.setBackground(new java.awt.Color(0, 153, 255));
        btnConsultarDoctor.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnConsultarDoctor.setText("CONSULTAR");
        btnConsultarDoctor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConsultarDoctorMouseClicked(evt);
            }
        });
        btnConsultarDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarDoctorActionPerformed(evt);
            }
        });

        txtNombreDoctor_ConsultaDoc1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtNombreDoctor_ConsultaDoc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreDoctor_ConsultaDoc1ActionPerformed(evt);
            }
        });

        Apellido_Paterno_ConsultDoc.setFont(new java.awt.Font("Segoe UI Black", 1, 16)); // NOI18N
        Apellido_Paterno_ConsultDoc.setForeground(new java.awt.Color(0, 51, 51));
        Apellido_Paterno_ConsultDoc.setText("APELLIDO PATERNO");

        Apellido_Materno_ConsultDoc.setFont(new java.awt.Font("Segoe UI Black", 1, 16)); // NOI18N
        Apellido_Materno_ConsultDoc.setForeground(new java.awt.Color(0, 51, 51));
        Apellido_Materno_ConsultDoc.setText("APELLIDO MATERNO");

        txtApellido_Paterno_ConsultaDoc1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtApellido_Paterno_ConsultaDoc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellido_Paterno_ConsultaDoc1ActionPerformed(evt);
            }
        });

        Especialidad_Doctor.setFont(new java.awt.Font("Segoe UI Black", 1, 16)); // NOI18N
        Especialidad_Doctor.setForeground(new java.awt.Color(0, 51, 51));
        Especialidad_Doctor.setText("ESPECIALIDAD");

        txtEspecialidad_ConsultaDoc.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtEspecialidad_ConsultaDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEspecialidad_ConsultaDocActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CuerpoLayout = new javax.swing.GroupLayout(Cuerpo);
        Cuerpo.setLayout(CuerpoLayout);
        CuerpoLayout.setHorizontalGroup(
            CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CuerpoLayout.createSequentialGroup()
                .addGroup(CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CuerpoLayout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(btnConsultarDoctor)
                        .addGap(61, 61, 61)
                        .addComponent(btnRegresarDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CuerpoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(30, 30, 30)
                        .addComponent(labelId_Doctor_ConsultaDoc)
                        .addGap(18, 18, 18)
                        .addComponent(txtId_Doctor_ConsultarDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(CuerpoLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Apellido_Paterno_ConsultDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Apellido_Materno_ConsultDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Especialidad_Doctor, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nombre_Doctor, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNombreDoctor_ConsultaDoc1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellido_Paterno_ConsultaDoc1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellido_Materno_Doc, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEspecialidad_ConsultaDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(132, 132, 132))
        );
        CuerpoLayout.setVerticalGroup(
            CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CuerpoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtId_Doctor_ConsultarDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelId_Doctor_ConsultaDoc)
                    .addComponent(jLabel1))
                .addGap(24, 24, 24)
                .addGroup(CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreDoctor_ConsultaDoc1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nombre_Doctor))
                .addGap(27, 27, 27)
                .addGroup(CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Apellido_Paterno_ConsultDoc)
                    .addComponent(txtApellido_Paterno_ConsultaDoc1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Apellido_Materno_ConsultDoc)
                    .addComponent(txtApellido_Materno_Doc, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Especialidad_Doctor)
                    .addComponent(txtEspecialidad_ConsultaDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegresarDoctor)
                    .addComponent(btnConsultarDoctor))
                .addGap(50, 50, 50))
        );

        jPanel1.add(Cuerpo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 630, 400));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void limpiarCajas(){
        txtNombreDoctor_ConsultaDoc1.setText(null);
        txtApellido_Paterno_ConsultaDoc1.setText(null);
        txtApellido_Materno_Doc.setText(null);
        txtEspecialidad_ConsultaDoc.setText(null);
    }
    private void txtId_Doctor_ConsultarDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtId_Doctor_ConsultarDocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtId_Doctor_ConsultarDocActionPerformed

    private void txtApellido_Materno_DocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellido_Materno_DocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellido_Materno_DocActionPerformed

    private void btnRegresarDoctorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarDoctorMouseClicked
        Principal_Administrador nuevaV = new Principal_Administrador();
        nuevaV.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarDoctorMouseClicked

    private void btnRegresarDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarDoctorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegresarDoctorActionPerformed

    private void btnConsultarDoctorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultarDoctorMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultarDoctorMouseClicked

    private void btnConsultarDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarDoctorActionPerformed
        Connection con = null;
        try {
            con = conectarBD.getConnection();
            conectarBD.ps = con.prepareStatement("SELECT * FROM doctor WHERE Id_Doctor = ?");
            conectarBD.ps.setString(1, txtId_Doctor_ConsultarDoc.getText());

            conectarBD.rs = conectarBD.ps.executeQuery(); //TRAER LOS RESULTADOS DE LA CONSULTA
            if(conectarBD.rs.next()){
                txtNombreDoctor_ConsultaDoc1.setText(conectarBD.rs.getString("Nombre_Doctor"));
                txtApellido_Paterno_ConsultaDoc1.setText(conectarBD.rs.getString("Apellido_Paterno_Doctor"));
                txtApellido_Materno_Doc.setText(conectarBD.rs.getString("Apellido_Materno_Doctor"));
                txtEspecialidad_ConsultaDoc.setText(conectarBD.rs.getString("Especialidad"));

            }else{
                JOptionPane.showMessageDialog(null, "NO SE ENCONTRARON RESULTADOS");
            }
            //EJECUTAR LA CONSULTA
            int res = conectarBD.ps.executeUpdate();
            if(res > 0){
                JOptionPane.showMessageDialog(null, "DOCTOR LOCALIZADO");
                limpiarCajas();
            }
            else{
                JOptionPane.showMessageDialog(null, "ERROR AL CONSULTAR DATOS DEL DOCTOR");
                limpiarCajas();
            }
            //CERRAR BD
            con.close();
        } catch (Exception e) {
            System.out.println("Error: "+e);
        }
    }//GEN-LAST:event_btnConsultarDoctorActionPerformed

    private void txtNombreDoctor_ConsultaDoc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreDoctor_ConsultaDoc1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreDoctor_ConsultaDoc1ActionPerformed

    private void txtApellido_Paterno_ConsultaDoc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellido_Paterno_ConsultaDoc1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellido_Paterno_ConsultaDoc1ActionPerformed

    private void txtEspecialidad_ConsultaDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEspecialidad_ConsultaDocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEspecialidad_ConsultaDocActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consultar_DoctorAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consultar_DoctorAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consultar_DoctorAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consultar_DoctorAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Consultar_DoctorAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Apellido_Materno_ConsultDoc;
    private javax.swing.JLabel Apellido_Paterno_ConsultDoc;
    private javax.swing.JPanel Cuerpo;
    private javax.swing.JLabel EncabezadoActualizar_Consultorio;
    private javax.swing.JPanel Encabezado_ConsultaDoc;
    private javax.swing.JLabel Especialidad_Doctor;
    private javax.swing.JLabel Nombre_Doctor;
    private javax.swing.JButton btnConsultarDoctor;
    private javax.swing.JButton btnRegresarDoctor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelId_Doctor_ConsultaDoc;
    private javax.swing.JTextField txtApellido_Materno_Doc;
    private javax.swing.JTextField txtApellido_Paterno_ConsultaDoc1;
    private javax.swing.JTextField txtEspecialidad_ConsultaDoc;
    private javax.swing.JTextField txtId_Doctor_ConsultarDoc;
    private javax.swing.JTextField txtNombreDoctor_ConsultaDoc1;
    // End of variables declaration//GEN-END:variables
}
