/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;

import Clases.Conectar;

/**
 *
 * @author rafae
 */
public class Disparador_Contar_Paciente extends javax.swing.JFrame {
    Conectar conectarBD = new Conectar();
    /**
     * Creates new form Disparador_ContarPaciente
     */
    
    public Disparador_Contar_Paciente() {
        initComponents();
        setLocationRelativeTo(null);
    }
 
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Encabezado_DisparadorContarPaciente = new javax.swing.JPanel();
        Encabezado_DisparadorContarPac = new javax.swing.JLabel();
        Cuerpo = new javax.swing.JPanel();
        Cantidad_Pacientes = new javax.swing.JLabel();
        txtCantidad_Pacientes = new javax.swing.JTextField();
        btnRegresarRegistrarPacienteAdmin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Encabezado_DisparadorContarPaciente.setBackground(new java.awt.Color(0, 153, 255));

        Encabezado_DisparadorContarPac.setFont(new java.awt.Font("Segoe UI Black", 0, 20)); // NOI18N
        Encabezado_DisparadorContarPac.setForeground(new java.awt.Color(255, 255, 255));
        Encabezado_DisparadorContarPac.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Encabezado_DisparadorContarPac.setText("DISPARADOR");

        javax.swing.GroupLayout Encabezado_DisparadorContarPacienteLayout = new javax.swing.GroupLayout(Encabezado_DisparadorContarPaciente);
        Encabezado_DisparadorContarPaciente.setLayout(Encabezado_DisparadorContarPacienteLayout);
        Encabezado_DisparadorContarPacienteLayout.setHorizontalGroup(
            Encabezado_DisparadorContarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Encabezado_DisparadorContarPacienteLayout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addComponent(Encabezado_DisparadorContarPac)
                .addContainerGap(201, Short.MAX_VALUE))
        );
        Encabezado_DisparadorContarPacienteLayout.setVerticalGroup(
            Encabezado_DisparadorContarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Encabezado_DisparadorContarPacienteLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Encabezado_DisparadorContarPac, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        jPanel1.add(Encabezado_DisparadorContarPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 60));

        Cuerpo.setBackground(new java.awt.Color(153, 204, 255));

        Cantidad_Pacientes.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        Cantidad_Pacientes.setForeground(new java.awt.Color(0, 51, 51));
        Cantidad_Pacientes.setText("CANTIDAD DE PACIENTES");

        txtCantidad_Pacientes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtCantidad_Pacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidad_PacientesActionPerformed(evt);
            }
        });

        btnRegresarRegistrarPacienteAdmin.setBackground(new java.awt.Color(0, 153, 255));
        btnRegresarRegistrarPacienteAdmin.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnRegresarRegistrarPacienteAdmin.setText("REGRESAR");
        btnRegresarRegistrarPacienteAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegresarRegistrarPacienteAdminMouseClicked(evt);
            }
        });
        btnRegresarRegistrarPacienteAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarRegistrarPacienteAdminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CuerpoLayout = new javax.swing.GroupLayout(Cuerpo);
        Cuerpo.setLayout(CuerpoLayout);
        CuerpoLayout.setHorizontalGroup(
            CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CuerpoLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(Cantidad_Pacientes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCantidad_Pacientes, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 64, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CuerpoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegresarRegistrarPacienteAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(189, 189, 189))
        );
        CuerpoLayout.setVerticalGroup(
            CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CuerpoLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cantidad_Pacientes)
                    .addComponent(txtCantidad_Pacientes, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(btnRegresarRegistrarPacienteAdmin)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel1.add(Cuerpo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 530, 160));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void limpiarCajas() {
        txtCantidad_Pacientes.setText(null);
    }
    
   
    
    private void txtCantidad_PacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidad_PacientesActionPerformed
       
    }//GEN-LAST:event_txtCantidad_PacientesActionPerformed

    private void btnRegresarRegistrarPacienteAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarRegistrarPacienteAdminMouseClicked
        Registro_PacienteAdmin nuevaV = new Registro_PacienteAdmin();
        nuevaV.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnRegresarRegistrarPacienteAdminMouseClicked

    private void btnRegresarRegistrarPacienteAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarRegistrarPacienteAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegresarRegistrarPacienteAdminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Disparador_Contar_Paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Disparador_Contar_Paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Disparador_Contar_Paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Disparador_Contar_Paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Disparador_Contar_Paciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cantidad_Pacientes;
    private javax.swing.JPanel Cuerpo;
    private javax.swing.JLabel Encabezado_DisparadorContarPac;
    private javax.swing.JPanel Encabezado_DisparadorContarPaciente;
    private javax.swing.JButton btnRegresarRegistrarPacienteAdmin;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JTextField txtCantidad_Pacientes;
    // End of variables declaration//GEN-END:variables
}
