/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;

import Clases.Conectar;
import java.sql.Connection;
import javax.swing.JOptionPane;
/**
 *
 * @author rafae
 */
public class Eliminar_ConsultorioA extends javax.swing.JFrame {
    Conectar conectarBD = new Conectar();
    /**
     * Creates new form Eliminar_ConsultorioA
     */
    public Eliminar_ConsultorioA() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        EncabezadoEliminarPaciente = new javax.swing.JPanel();
        Nombre_Encabezado = new javax.swing.JLabel();
        Cuerpo = new javax.swing.JPanel();
        labelId_ConsultorioEl = new javax.swing.JLabel();
        txtId_ConsultoriorEli = new javax.swing.JTextField();
        btnRegresarConsultorioE = new javax.swing.JButton();
        btnEliminarConsultorioEli = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        EncabezadoEliminarPaciente.setBackground(new java.awt.Color(0, 153, 255));

        Nombre_Encabezado.setFont(new java.awt.Font("Segoe UI Black", 0, 20)); // NOI18N
        Nombre_Encabezado.setForeground(new java.awt.Color(255, 255, 255));
        Nombre_Encabezado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Nombre_Encabezado.setText("ELIMINAR CONSULTORIO");

        javax.swing.GroupLayout EncabezadoEliminarPacienteLayout = new javax.swing.GroupLayout(EncabezadoEliminarPaciente);
        EncabezadoEliminarPaciente.setLayout(EncabezadoEliminarPacienteLayout);
        EncabezadoEliminarPacienteLayout.setHorizontalGroup(
            EncabezadoEliminarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EncabezadoEliminarPacienteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Nombre_Encabezado)
                .addGap(170, 170, 170))
        );
        EncabezadoEliminarPacienteLayout.setVerticalGroup(
            EncabezadoEliminarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EncabezadoEliminarPacienteLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Nombre_Encabezado, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        jPanel1.add(EncabezadoEliminarPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 60));

        Cuerpo.setBackground(new java.awt.Color(153, 204, 255));

        labelId_ConsultorioEl.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        labelId_ConsultorioEl.setForeground(new java.awt.Color(0, 51, 51));
        labelId_ConsultorioEl.setText("ID CONSULTORIO (5)");

        txtId_ConsultoriorEli.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtId_ConsultoriorEli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtId_ConsultoriorEliActionPerformed(evt);
            }
        });

        btnRegresarConsultorioE.setBackground(new java.awt.Color(0, 153, 255));
        btnRegresarConsultorioE.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnRegresarConsultorioE.setText("REGRESAR");
        btnRegresarConsultorioE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegresarConsultorioEMouseClicked(evt);
            }
        });
        btnRegresarConsultorioE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarConsultorioEActionPerformed(evt);
            }
        });

        btnEliminarConsultorioEli.setBackground(new java.awt.Color(0, 153, 255));
        btnEliminarConsultorioEli.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnEliminarConsultorioEli.setText("ELIMINAR");
        btnEliminarConsultorioEli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarConsultorioEliMouseClicked(evt);
            }
        });
        btnEliminarConsultorioEli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarConsultorioEliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CuerpoLayout = new javax.swing.GroupLayout(Cuerpo);
        Cuerpo.setLayout(CuerpoLayout);
        CuerpoLayout.setHorizontalGroup(
            CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CuerpoLayout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(btnEliminarConsultorioEli, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86)
                .addComponent(btnRegresarConsultorioE, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CuerpoLayout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addComponent(labelId_ConsultorioEl)
                .addGap(67, 67, 67)
                .addComponent(txtId_ConsultoriorEli, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );
        CuerpoLayout.setVerticalGroup(
            CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CuerpoLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelId_ConsultorioEl)
                    .addComponent(txtId_ConsultoriorEli, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegresarConsultorioE, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarConsultorioEli, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        jPanel1.add(Cuerpo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 650, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void limpiarCajas(){
        txtId_ConsultoriorEli.setText(null);
    }
    
    private void txtId_ConsultoriorEliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtId_ConsultoriorEliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtId_ConsultoriorEliActionPerformed

    private void btnRegresarConsultorioEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarConsultorioEMouseClicked
        Principal_Administrador nuevaV = new Principal_Administrador();
        nuevaV.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarConsultorioEMouseClicked

    private void btnRegresarConsultorioEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarConsultorioEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegresarConsultorioEActionPerformed

    private void btnEliminarConsultorioEliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarConsultorioEliMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarConsultorioEliMouseClicked

    private void btnEliminarConsultorioEliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarConsultorioEliActionPerformed
        Connection con = null;
        try {
            con = conectarBD.getConnection();
            conectarBD.ps = con.prepareStatement("DELETE FROM consultorio WHERE Id_Consultorio= ?");
            conectarBD.ps.setString(1, txtId_ConsultoriorEli.getText());

            //EJECUTAR LA CONSULTA
            int res = conectarBD.ps.executeUpdate();
            if(res > 0){
                JOptionPane.showMessageDialog(null, "CONSULTORIO ELIMINADO");
                limpiarCajas();
            }
            else{
                JOptionPane.showMessageDialog(null, "VERIFICA EL Id_Consultorio");
                limpiarCajas();
            }
            //CERRAR BD
            con.close();
        } catch (Exception e) {
            System.err.println("Error: "+e);
        }
    }//GEN-LAST:event_btnEliminarConsultorioEliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Eliminar_ConsultorioA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Eliminar_ConsultorioA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Eliminar_ConsultorioA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Eliminar_ConsultorioA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Eliminar_ConsultorioA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Cuerpo;
    private javax.swing.JPanel EncabezadoEliminarPaciente;
    private javax.swing.JLabel Nombre_Encabezado;
    private javax.swing.JButton btnEliminarConsultorioEli;
    private javax.swing.JButton btnRegresarConsultorioE;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelId_ConsultorioEl;
    private javax.swing.JTextField txtId_ConsultoriorEli;
    // End of variables declaration//GEN-END:variables
}
