/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;
import Clases.Conectar;
import java.sql.Connection;
import javax.swing.JOptionPane;

/**
 *
 * @author sandybau
 */
public class Eliminar_DoctorAdmin extends javax.swing.JFrame {
    Conectar conectarBD = new Conectar();

    /**
     * Creates new form Elkiminar_DoctorAdmin
     */
    public Eliminar_DoctorAdmin() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Encabezado = new javax.swing.JPanel();
        Nombre_Encabezado = new javax.swing.JLabel();
        Cuerpo = new javax.swing.JPanel();
        NumeroIdentificacion = new javax.swing.JLabel();
        txtNumeroIdentificacion = new javax.swing.JTextField();
        btnEliminarDoctor = new javax.swing.JButton();
        btnRegresarDoctor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Encabezado.setBackground(new java.awt.Color(0, 153, 255));
        Encabezado.setPreferredSize(new java.awt.Dimension(690, 60));

        Nombre_Encabezado.setFont(new java.awt.Font("Segoe UI Black", 0, 20)); // NOI18N
        Nombre_Encabezado.setForeground(new java.awt.Color(255, 255, 255));
        Nombre_Encabezado.setText("BORRAR DOCTOR");

        javax.swing.GroupLayout EncabezadoLayout = new javax.swing.GroupLayout(Encabezado);
        Encabezado.setLayout(EncabezadoLayout);
        EncabezadoLayout.setHorizontalGroup(
            EncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EncabezadoLayout.createSequentialGroup()
                .addGap(245, 245, 245)
                .addComponent(Nombre_Encabezado)
                .addContainerGap(268, Short.MAX_VALUE))
        );
        EncabezadoLayout.setVerticalGroup(
            EncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EncabezadoLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(Nombre_Encabezado)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel1.add(Encabezado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 60));

        Cuerpo.setBackground(new java.awt.Color(153, 204, 255));

        NumeroIdentificacion.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        NumeroIdentificacion.setForeground(new java.awt.Color(0, 51, 51));
        NumeroIdentificacion.setText("NUMERO DE IDENTIFICACION (10)");

        txtNumeroIdentificacion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtNumeroIdentificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroIdentificacionActionPerformed(evt);
            }
        });

        btnEliminarDoctor.setBackground(new java.awt.Color(0, 153, 255));
        btnEliminarDoctor.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnEliminarDoctor.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarDoctor.setText("ELIMINAR");
        btnEliminarDoctor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarDoctorMouseClicked(evt);
            }
        });
        btnEliminarDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarDoctorActionPerformed(evt);
            }
        });

        btnRegresarDoctor.setBackground(new java.awt.Color(0, 153, 255));
        btnRegresarDoctor.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnRegresarDoctor.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresarDoctor.setText("REGRESAR");
        btnRegresarDoctor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegresarDoctorMouseClicked(evt);
            }
        });
        btnRegresarDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarDoctorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CuerpoLayout = new javax.swing.GroupLayout(Cuerpo);
        Cuerpo.setLayout(CuerpoLayout);
        CuerpoLayout.setHorizontalGroup(
            CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CuerpoLayout.createSequentialGroup()
                .addGroup(CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CuerpoLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(NumeroIdentificacion)
                        .addGap(18, 18, 18)
                        .addComponent(txtNumeroIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CuerpoLayout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(btnEliminarDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(btnRegresarDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        CuerpoLayout.setVerticalGroup(
            CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CuerpoLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NumeroIdentificacion)
                    .addComponent(txtNumeroIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminarDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegresarDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
        );

        jPanel1.add(Cuerpo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 690, 220));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void limpiarCajas(){
        txtNumeroIdentificacion.setText(null);
    }
    private void btnRegresarDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarDoctorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegresarDoctorActionPerformed

    private void btnRegresarDoctorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarDoctorMouseClicked
        Principal_Administrador nuevaV = new Principal_Administrador();
        nuevaV.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarDoctorMouseClicked

    private void btnEliminarDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarDoctorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarDoctorActionPerformed

    private void btnEliminarDoctorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarDoctorMouseClicked
        // TODO add your handling code here:
        Connection  con = null;
        try{
            con = conectarBD.getConnection();
            conectarBD.ps = con.prepareStatement("DELETE FROM doctor WHERE Id_Doctor= ?");
            conectarBD.ps.setString(1, txtNumeroIdentificacion.getText());

            //EJECUTAR LA CONSULTA
            int res = conectarBD.ps.executeUpdate();
            if(res > 0){
                JOptionPane.showMessageDialog(null, "DOCTOR ELIMINADO");
                limpiarCajas();
            }
            else{
                JOptionPane.showMessageDialog(null, "ERROR AL BORRAR DOCTOR");
                limpiarCajas();
            }

            con.close();

        }catch(Exception e){
            System.err.println(e);
        }
    }//GEN-LAST:event_btnEliminarDoctorMouseClicked

    private void txtNumeroIdentificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroIdentificacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroIdentificacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Eliminar_DoctorAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Eliminar_DoctorAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Eliminar_DoctorAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Eliminar_DoctorAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Eliminar_DoctorAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Cuerpo;
    private javax.swing.JPanel Encabezado;
    private javax.swing.JLabel Nombre_Encabezado;
    private javax.swing.JLabel NumeroIdentificacion;
    private javax.swing.JButton btnEliminarDoctor;
    private javax.swing.JButton btnRegresarDoctor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtNumeroIdentificacion;
    // End of variables declaration//GEN-END:variables
}
