/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;
import Clases.Conectar;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;


import javax.swing.JOptionPane;

/**
 *
 * @author rafael
 */
public class Login_BD extends javax.swing.JFrame {
    Conectar conectarBD = new Conectar();
    String Verificacion = "Null";
    int contadorIntentos = 0;
    String currentCaptcha;
    //IDENTIFICADOR
    String SESSION = "";
    
    public Login_BD() {
        initComponents();
        lblImg.setText("");
        setLocationRelativeTo(null);
        generar();
    }
    private void limpiarCajas(){
        //jComboBox_Usuarios.setSelectedIndex("SELECCIONE USUARIO");
        txtContrasena.setText(null);
    }
    
    public void generar(){
        try {
        currentCaptcha = textoGraphics.generateImage();
        //System.out.println(currentCaptcha);
        
        File archivo = new File(System.getProperty("user.dir") + "/captcha/Text.png");
        
        //Limpiar cache para que lea la imagen
        ImageIO.setUseCache(false);
        
        Image img = ImageIO.read(archivo);
        lblImg.setIcon(new ImageIcon(img));
        lblImg.revalidate();
        lblImg.repaint();
        
    } catch (IOException e) {
        e.printStackTrace();
    }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCurpPacienteE = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtContrasena = new javax.swing.JPasswordField();
        btnIngresar = new javax.swing.JButton();
        jComboBox_Usuarios = new javax.swing.JComboBox<>();
        lblImg = new javax.swing.JLabel();
        txtCaptcha = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        txtCurpPacienteE.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtCurpPacienteE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCurpPacienteEActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 204, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        jLabel1.setText("҉ HOSPITAL LOS GIRASOLES ҉ ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(71, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(49, 49, 49))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 60));

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));

        jLabel6.setFont(new java.awt.Font("Microsoft Sans Serif", 2, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("BIENVENIDO");

        jLabel3.setFont(new java.awt.Font("Microsoft Sans Serif", 2, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("INICIO DE SESIÓN");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("USUARIO");

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("CONTRASEÑA");

        txtContrasena.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtContrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContrasenaActionPerformed(evt);
            }
        });

        btnIngresar.setText("Ingresar");
        btnIngresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIngresarMouseClicked(evt);
            }
        });
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        jComboBox_Usuarios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECIONE USUARIO", "RECEPCIONISTA", "ADMINISTRADOR", "DOCTOR", "PACIENTE", " " }));
        jComboBox_Usuarios.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_UsuariosItemStateChanged(evt);
            }
        });
        jComboBox_Usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_UsuariosActionPerformed(evt);
            }
        });

        lblImg.setText(" ");

        txtCaptcha.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("CAPTCHA:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(btnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblImg, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7)
                                .addComponent(txtContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jComboBox_Usuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addGap(26, 26, 26)
                                    .addComponent(txtCaptcha, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox_Usuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(txtContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblImg, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCaptcha, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addComponent(btnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 460, 390));

        jPanel4.setBackground(new java.awt.Color(0, 153, 255));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/imagen_Hospital.jpg"))); // NOI18N

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("© RELS_HOSPITAL_TBD ȣ");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel5))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, 230, 390));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContrasenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContrasenaActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
   
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void btnIngresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIngresarMouseClicked
        
        //USUARIOS
        String usuario1 = "RECEPCIONISTA";
        String usuario2 = "PACIENTE";
        String usuario3 = "DOCTOR";
        String usuario4 = "ADMINISTRADOR";

        //Contraseñas
        String contraUsuario1 = "recepcion512";
        String contraUsuario2 = "paciente159";
        String contraUsuario3 = "doctor999";
        String contraUsuario4 = "administrador221";
        
        //VERIFICAR CAPTCHA
        String captchaCorrecto;
        
        String txtContrasenaA = new String(txtContrasena.getPassword());
     
        if(jComboBox_Usuarios.getSelectedItem().equals(usuario1) && txtContrasenaA.equals(contraUsuario1) 
                && txtCaptcha.getText().equals(currentCaptcha)){
            //RECEPCIONISTA
             JOptionPane.showMessageDialog(this, "DATOS CORRECTOS");
             SESSION = "1";
             ViewPerfilesA perfil = new ViewPerfilesA();
             perfil.consultarUsuario(SESSION); 
             System.out.println("VARIABLE SESION: "+SESSION+" PERTENECIENTE A: "+ usuario1);
             this.Verificacion="VERDADERO";
             PrincipalRecepcionista nuevaV = new PrincipalRecepcionista();
             nuevaV.setVisible(true);
             IngresarLogin();
             this.dispose();
         
        }else
        if(jComboBox_Usuarios.getSelectedItem().equals(usuario2) && txtContrasenaA.equals(contraUsuario2) 
                && txtCaptcha.getText().equals(currentCaptcha)){
            //PACIENTE
             JOptionPane.showMessageDialog(this, "DATOS CORRECTOS");
             SESSION = "2";
             ViewPerfilesA perfil = new ViewPerfilesA();
             perfil.consultarUsuario(SESSION); 
             System.out.println("VARIABLE SESION: "+SESSION+" PERTENECIENTE A: "+ usuario2);
             this.Verificacion="VERDADERO";
             PrincipalPaciente nuevaV = new PrincipalPaciente();
             nuevaV.setVisible(true);
             IngresarLogin();
             this.dispose();
        }else
        if(jComboBox_Usuarios.getSelectedItem().equals(usuario3) && txtContrasenaA.equals(contraUsuario3) 
                && txtCaptcha.getText().equals(currentCaptcha)){
            //DOCTOR
             JOptionPane.showMessageDialog(this, "DATOS CORRECTOS");
             SESSION = "3";
             ViewPerfilesA perfil = new ViewPerfilesA();
             perfil.consultarUsuario(SESSION); 
             System.out.println("VARIABLE SESION: "+SESSION+" PERTENECIENTE A: "+ usuario3);
             this.Verificacion="VERDADERO";
             Principal_Doctor nuevaV = new Principal_Doctor();
             nuevaV.setVisible(true);
             IngresarLogin();
             this.dispose();
        }else
        if(jComboBox_Usuarios.getSelectedItem().equals(usuario4) && txtContrasenaA.equals(contraUsuario4) 
                && txtCaptcha.getText().equals(currentCaptcha)){
            //ADMINISTRADOR
             JOptionPane.showMessageDialog(this, "DATOS CORRECTOS");
             SESSION = "4";
             ViewPerfilesA perfil = new ViewPerfilesA();
             perfil.consultarUsuario(SESSION); 
             System.out.println("VARIABLE SESION: "+SESSION+" PERTENECIENTE A: "+ usuario4);
             this.Verificacion="VERDADERO";
             Principal_Administrador nuevaV = new Principal_Administrador();
             nuevaV.setVisible(true);
             IngresarLogin();
             this.dispose();
        }else {
            //Intentos agotados
            if(this.contadorIntentos >= 3) {
                JOptionPane.showMessageDialog(this, "NÚMERO DE INTENTOS AGOTADO. LA VENTANA SE CERRARÁ.");       
                dispose(); // Cerrar la ventana
                //Quedan intentos, verifica el captcha primero
            } else if(!txtCaptcha.getText().equals(currentCaptcha)){
                JOptionPane.showMessageDialog(null, "EL CAPTCHA ES INCORRECTO, INTENTA DE NUEVO");
                txtCaptcha.setText(null);
                generar();
            }else {
                // El captcha es diferente, entonces el usuario y contraseña son incorrectos
                // Incrementar el contador de intentos solo en caso de intentos fallidos
                this.contadorIntentos++;
                this.Verificacion="INCORRECTO";
                JOptionPane.showMessageDialog(null, "USUARIO Y CONTRASEÑA INCORRECTOS");
                
                JOptionPane.showMessageDialog(this, "INTENTOS RESTANTES: " + (3 - this.contadorIntentos));
                IngresarLogin();
                limpiarCajas();   
                
                //Verifica que haya intentos
                if(this.contadorIntentos >= 3) {
                JOptionPane.showMessageDialog(this, "NÚMERO DE INTENTOS AGOTADO. LA VENTANA SE CERRARÁ.");       
                dispose(); // Cerrar la ventana
                }
            }
            
            /*
            //Caso de que usuario, contraseña y captcha esten mal
            
            // Validar credenciales ingresadas
                String usuarioSeleccionado = (String) jComboBox_Usuarios.getSelectedItem();
                String contrasenaIngresada = new String(txtContrasena.getPassword());

                boolean credencialesValidas = false;
                
                    if ((usuarioSeleccionado.equals(usuario1) && contrasenaIngresada.equals(contraUsuario1)) ||
                (usuarioSeleccionado.equals(usuario2) && contrasenaIngresada.equals(contraUsuario2)) ||
                (usuarioSeleccionado.equals(usuario3) && contrasenaIngresada.equals(contraUsuario3)) ||
                (usuarioSeleccionado.equals(usuario4) && contrasenaIngresada.equals(contraUsuario4))) {
                    if(!txtCaptcha.getText().equals(currentCaptcha)){
                    JOptionPane.showMessageDialog(null, "EL CAPTCHA ES INCORRECTO, INTENTA DE NUEVO");
                    txtCaptcha.setText(null);
                    generar();
                    }
            }else
            {
                // Incrementar el contador de intentos solo en caso de intentos fallidos
                this.contadorIntentos++;
                this.Verificacion="INCORRECTO";
                JOptionPane.showMessageDialog(this, "DATOS INCORRECTOS. INTENTOS RESTANTES: " + (3 - this.contadorIntentos));
                IngresarLogin();
                limpiarCajas();
                
                //Verifica que haya intentos
                if(this.contadorIntentos >= 3) {
                JOptionPane.showMessageDialog(this, "NÚMERO DE INTENTOS AGOTADO. LA VENTANA SE CERRARÁ.");       
                dispose(); // Cerrar la ventana
                }    
           }*/
        }               
    }//GEN-LAST:event_btnIngresarMouseClicked
    private void IngresarLogin(){
        Connection  con = null;
        try{
            con = conectarBD.getConnection();
            conectarBD.ps = con.prepareStatement("INSERT INTO sesion (Rol_Usuario, Contrasena_Ingresada, Verificacion, Fecha_Entrada, Hora_Entrada, No_Intentos_Fallidos) VALUES (?,?,?,?,?,?)");
            conectarBD.ps.setString(1,jComboBox_Usuarios.getSelectedItem().toString());
            conectarBD.ps.setString(2,txtContrasena.getText());
            conectarBD.ps.setString(3,this.Verificacion);
            LocalDateTime fechaHoraActual = LocalDateTime.now();
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
            String fechaFormateada = fechaHoraActual.format(formatter);
            conectarBD.ps.setString(4, fechaFormateada);
            DateTimeFormatter formatterHora = DateTimeFormatter.ofPattern("HH:mm:ss");
            String horaFormateada = fechaHoraActual.format(formatterHora);
            conectarBD.ps.setString(5, horaFormateada);
            conectarBD.ps.setString(6, String.valueOf(contadorIntentos));
            
            //System.out.println(jComboBox_Usuarios.getSelectedItem().toString());
            //System.out.println(txtContrasena.getText());
            //System.out.println(this.Verificacion);
            //System.out.println(horaFormateada);
            //System.out.println(String.valueOf(contadorIntentos));
            

            //EJECUTAR LA CONSULTA
            int res = conectarBD.ps.executeUpdate();
            if(res > 0){
            
                //limpiarCajas();
            }
            else{
                
                //limpiarCajas();
            }

            con.close();

        }catch(Exception e){
            System.err.println(e);
        }
    }
    private void jComboBox_UsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_UsuariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_UsuariosActionPerformed

    private void jComboBox_UsuariosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_UsuariosItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_UsuariosItemStateChanged

    private void txtCurpPacienteEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCurpPacienteEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCurpPacienteEActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JComboBox<String> jComboBox_Usuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblImg;
    private javax.swing.JTextField txtCaptcha;
    private javax.swing.JPasswordField txtContrasena;
    private javax.swing.JTextField txtCurpPacienteE;
    // End of variables declaration//GEN-END:variables
}