/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;
import Formularios.Login_BD;

/**
 *
 * @author sandybau
 */
public class Principal_Administrador extends javax.swing.JFrame {

    /**
     * Creates new form Principal_Administrador
     */
    public Principal_Administrador() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Encabezado = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        OpcionestablaDoctor = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnRegistrarPacienteT = new javax.swing.JButton();
        btnInsertarConsultorioR = new javax.swing.JButton();
        btnPerfilAdministrador = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnConsultarPaciente_Admin = new javax.swing.JButton();
        btnActualizarPaciente_Admin = new javax.swing.JButton();
        btnInsertarHorario_Admin = new javax.swing.JButton();
        btnBorrarHorario_Admin = new javax.swing.JButton();
        btnActualizarHorario_Admin = new javax.swing.JButton();
        btnConsultarHorario_Admin = new javax.swing.JButton();
        btnBorrarDoctor_Admin = new javax.swing.JButton();
        btnActualizarDoctor_Admin = new javax.swing.JButton();
        btnConsultarDoctor_Admin = new javax.swing.JButton();
        btnInsertarConsultorio_Admin = new javax.swing.JButton();
        btnBorrarConsultorio_Admin = new javax.swing.JButton();
        btnActualizarConsultorio_Admin = new javax.swing.JButton();
        btnConsultarConsultorio_Admin = new javax.swing.JButton();
        btnInsertarDoctor_Admin = new javax.swing.JButton();
        btnBorrarPaciente_Admin = new javax.swing.JButton();
        btnInsertarPaciente_Admin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Encabezado.setBackground(new java.awt.Color(255, 255, 153));

        jLabel1.setBackground(new java.awt.Color(0, 102, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("ADMINISTRADOR");

        OpcionestablaDoctor.setBackground(new java.awt.Color(0, 153, 153));
        OpcionestablaDoctor.setForeground(new java.awt.Color(0, 153, 153));

        jLabel2.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("DOCTOR");

        jLabel3.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("PACIENTE");

        jLabel4.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("CONSULTORIO");

        jLabel5.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("HORARIO");

        javax.swing.GroupLayout OpcionestablaDoctorLayout = new javax.swing.GroupLayout(OpcionestablaDoctor);
        OpcionestablaDoctor.setLayout(OpcionestablaDoctorLayout);
        OpcionestablaDoctorLayout.setHorizontalGroup(
            OpcionestablaDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OpcionestablaDoctorLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(jLabel4)
                .addGap(37, 37, 37))
        );
        OpcionestablaDoctorLayout.setVerticalGroup(
            OpcionestablaDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OpcionestablaDoctorLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(OpcionestablaDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(15, 15, 15))
        );

        btnRegistrarPacienteT.setBackground(new java.awt.Color(255, 204, 102));
        btnRegistrarPacienteT.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnRegistrarPacienteT.setForeground(new java.awt.Color(0, 51, 51));
        btnRegistrarPacienteT.setText("TRANSACCIONES");
        btnRegistrarPacienteT.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRegistrarPacienteT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistrarPacienteTMouseClicked(evt);
            }
        });
        btnRegistrarPacienteT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarPacienteTActionPerformed(evt);
            }
        });

        btnInsertarConsultorioR.setBackground(new java.awt.Color(255, 0, 51));
        btnInsertarConsultorioR.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnInsertarConsultorioR.setForeground(new java.awt.Color(255, 255, 255));
        btnInsertarConsultorioR.setText("LOGIN");
        btnInsertarConsultorioR.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnInsertarConsultorioR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarConsultorioRActionPerformed(evt);
            }
        });

        btnPerfilAdministrador.setBackground(new java.awt.Color(255, 204, 102));
        btnPerfilAdministrador.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnPerfilAdministrador.setForeground(new java.awt.Color(0, 51, 51));
        btnPerfilAdministrador.setText("PERFIL");
        btnPerfilAdministrador.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPerfilAdministrador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPerfilAdministradorMouseClicked(evt);
            }
        });
        btnPerfilAdministrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerfilAdministradorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout EncabezadoLayout = new javax.swing.GroupLayout(Encabezado);
        Encabezado.setLayout(EncabezadoLayout);
        EncabezadoLayout.setHorizontalGroup(
            EncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EncabezadoLayout.createSequentialGroup()
                .addGroup(EncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, EncabezadoLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRegistrarPacienteT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnInsertarConsultorioR, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPerfilAdministrador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(EncabezadoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(OpcionestablaDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0))
        );
        EncabezadoLayout.setVerticalGroup(
            EncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EncabezadoLayout.createSequentialGroup()
                .addGroup(EncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(EncabezadoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, EncabezadoLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(EncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRegistrarPacienteT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnInsertarConsultorioR, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPerfilAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(OpcionestablaDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(Encabezado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 70));

        jPanel5.setBackground(new java.awt.Color(0, 153, 153));
        jPanel5.setForeground(new java.awt.Color(0, 153, 153));

        jLabel6.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("DOCTOR");

        jLabel7.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("PACIENTE");

        jLabel8.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("CONSULTORIO");

        jLabel9.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("HORARIO");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(jLabel8)
                .addGap(37, 37, 37))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(15, 15, 15))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 710, 70));

        jPanel4.setBackground(new java.awt.Color(153, 204, 255));

        btnConsultarPaciente_Admin.setBackground(new java.awt.Color(153, 255, 153));
        btnConsultarPaciente_Admin.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnConsultarPaciente_Admin.setForeground(new java.awt.Color(0, 51, 51));
        btnConsultarPaciente_Admin.setText("CONSULTAR");
        btnConsultarPaciente_Admin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnConsultarPaciente_Admin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConsultarPaciente_AdminMouseClicked(evt);
            }
        });
        btnConsultarPaciente_Admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarPaciente_AdminActionPerformed(evt);
            }
        });

        btnActualizarPaciente_Admin.setBackground(new java.awt.Color(153, 255, 153));
        btnActualizarPaciente_Admin.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnActualizarPaciente_Admin.setForeground(new java.awt.Color(0, 51, 51));
        btnActualizarPaciente_Admin.setText("ACTUALIZAR");
        btnActualizarPaciente_Admin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnActualizarPaciente_Admin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnActualizarPaciente_AdminMouseClicked(evt);
            }
        });
        btnActualizarPaciente_Admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarPaciente_AdminActionPerformed(evt);
            }
        });

        btnInsertarHorario_Admin.setBackground(new java.awt.Color(255, 204, 102));
        btnInsertarHorario_Admin.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnInsertarHorario_Admin.setForeground(new java.awt.Color(0, 51, 51));
        btnInsertarHorario_Admin.setText("INSERTAR");
        btnInsertarHorario_Admin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnInsertarHorario_Admin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInsertarHorario_AdminMouseClicked(evt);
            }
        });
        btnInsertarHorario_Admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarHorario_AdminActionPerformed(evt);
            }
        });

        btnBorrarHorario_Admin.setBackground(new java.awt.Color(255, 204, 102));
        btnBorrarHorario_Admin.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnBorrarHorario_Admin.setForeground(new java.awt.Color(0, 51, 51));
        btnBorrarHorario_Admin.setText("BORRAR");
        btnBorrarHorario_Admin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBorrarHorario_Admin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBorrarHorario_AdminMouseClicked(evt);
            }
        });
        btnBorrarHorario_Admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarHorario_AdminActionPerformed(evt);
            }
        });

        btnActualizarHorario_Admin.setBackground(new java.awt.Color(255, 204, 102));
        btnActualizarHorario_Admin.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnActualizarHorario_Admin.setForeground(new java.awt.Color(0, 51, 51));
        btnActualizarHorario_Admin.setText("ACTUALIZAR");
        btnActualizarHorario_Admin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnActualizarHorario_Admin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnActualizarHorario_AdminMouseClicked(evt);
            }
        });
        btnActualizarHorario_Admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarHorario_AdminActionPerformed(evt);
            }
        });

        btnConsultarHorario_Admin.setBackground(new java.awt.Color(255, 204, 102));
        btnConsultarHorario_Admin.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnConsultarHorario_Admin.setForeground(new java.awt.Color(0, 51, 51));
        btnConsultarHorario_Admin.setText("CONSULTAR");
        btnConsultarHorario_Admin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnConsultarHorario_Admin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConsultarHorario_AdminMouseClicked(evt);
            }
        });
        btnConsultarHorario_Admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarHorario_AdminActionPerformed(evt);
            }
        });

        btnBorrarDoctor_Admin.setBackground(new java.awt.Color(153, 255, 153));
        btnBorrarDoctor_Admin.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnBorrarDoctor_Admin.setForeground(new java.awt.Color(0, 51, 51));
        btnBorrarDoctor_Admin.setText("BORRAR");
        btnBorrarDoctor_Admin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBorrarDoctor_Admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarDoctor_AdminActionPerformed(evt);
            }
        });

        btnActualizarDoctor_Admin.setBackground(new java.awt.Color(153, 255, 153));
        btnActualizarDoctor_Admin.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnActualizarDoctor_Admin.setForeground(new java.awt.Color(0, 51, 51));
        btnActualizarDoctor_Admin.setText("ACTUALIZAR");
        btnActualizarDoctor_Admin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnActualizarDoctor_Admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarDoctor_AdminActionPerformed(evt);
            }
        });

        btnConsultarDoctor_Admin.setBackground(new java.awt.Color(153, 255, 153));
        btnConsultarDoctor_Admin.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnConsultarDoctor_Admin.setForeground(new java.awt.Color(0, 51, 51));
        btnConsultarDoctor_Admin.setText("CONSULTAR");
        btnConsultarDoctor_Admin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnConsultarDoctor_Admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarDoctor_AdminActionPerformed(evt);
            }
        });

        btnInsertarConsultorio_Admin.setBackground(new java.awt.Color(255, 204, 102));
        btnInsertarConsultorio_Admin.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnInsertarConsultorio_Admin.setForeground(new java.awt.Color(0, 51, 51));
        btnInsertarConsultorio_Admin.setText("INSERTAR");
        btnInsertarConsultorio_Admin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnInsertarConsultorio_Admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarConsultorio_AdminActionPerformed(evt);
            }
        });

        btnBorrarConsultorio_Admin.setBackground(new java.awt.Color(255, 204, 102));
        btnBorrarConsultorio_Admin.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnBorrarConsultorio_Admin.setForeground(new java.awt.Color(0, 51, 51));
        btnBorrarConsultorio_Admin.setText("BORRAR");
        btnBorrarConsultorio_Admin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBorrarConsultorio_Admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarConsultorio_AdminActionPerformed(evt);
            }
        });

        btnActualizarConsultorio_Admin.setBackground(new java.awt.Color(255, 204, 102));
        btnActualizarConsultorio_Admin.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnActualizarConsultorio_Admin.setForeground(new java.awt.Color(0, 51, 51));
        btnActualizarConsultorio_Admin.setText("ACTUALIZAR");
        btnActualizarConsultorio_Admin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnActualizarConsultorio_Admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarConsultorio_AdminActionPerformed(evt);
            }
        });

        btnConsultarConsultorio_Admin.setBackground(new java.awt.Color(255, 204, 102));
        btnConsultarConsultorio_Admin.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnConsultarConsultorio_Admin.setForeground(new java.awt.Color(0, 51, 51));
        btnConsultarConsultorio_Admin.setText("CONSULTAR");
        btnConsultarConsultorio_Admin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnConsultarConsultorio_Admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarConsultorio_AdminActionPerformed(evt);
            }
        });

        btnInsertarDoctor_Admin.setBackground(new java.awt.Color(153, 255, 153));
        btnInsertarDoctor_Admin.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnInsertarDoctor_Admin.setForeground(new java.awt.Color(0, 51, 51));
        btnInsertarDoctor_Admin.setText("INSERTAR");
        btnInsertarDoctor_Admin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnInsertarDoctor_Admin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInsertarDoctor_AdminMouseClicked(evt);
            }
        });
        btnInsertarDoctor_Admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarDoctor_AdminActionPerformed(evt);
            }
        });

        btnBorrarPaciente_Admin.setBackground(new java.awt.Color(153, 255, 153));
        btnBorrarPaciente_Admin.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnBorrarPaciente_Admin.setForeground(new java.awt.Color(0, 51, 51));
        btnBorrarPaciente_Admin.setText("BORRAR");
        btnBorrarPaciente_Admin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBorrarPaciente_Admin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBorrarPaciente_AdminMouseClicked(evt);
            }
        });
        btnBorrarPaciente_Admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarPaciente_AdminActionPerformed(evt);
            }
        });

        btnInsertarPaciente_Admin.setBackground(new java.awt.Color(153, 255, 153));
        btnInsertarPaciente_Admin.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnInsertarPaciente_Admin.setForeground(new java.awt.Color(0, 51, 51));
        btnInsertarPaciente_Admin.setText("INSERTAR");
        btnInsertarPaciente_Admin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnInsertarPaciente_Admin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInsertarPaciente_AdminMouseClicked(evt);
            }
        });
        btnInsertarPaciente_Admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarPaciente_AdminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnConsultarPaciente_Admin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnActualizarPaciente_Admin, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                    .addComponent(btnBorrarPaciente_Admin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnInsertarPaciente_Admin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(67, 67, 67)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnConsultarHorario_Admin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBorrarHorario_Admin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnInsertarHorario_Admin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnActualizarHorario_Admin, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnConsultarDoctor_Admin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBorrarDoctor_Admin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnActualizarDoctor_Admin, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInsertarDoctor_Admin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnConsultarConsultorio_Admin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBorrarConsultorio_Admin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnInsertarConsultorio_Admin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnActualizarConsultorio_Admin, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(btnInsertarConsultorio_Admin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(btnBorrarConsultorio_Admin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(btnActualizarConsultorio_Admin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGap(217, 217, 217)
                                .addComponent(btnConsultarConsultorio_Admin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 39, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnInsertarHorario_Admin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnInsertarDoctor_Admin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnInsertarPaciente_Admin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBorrarHorario_Admin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBorrarPaciente_Admin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addComponent(btnActualizarHorario_Admin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(btnBorrarDoctor_Admin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(btnActualizarDoctor_Admin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnConsultarDoctor_Admin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(137, 137, 137)
                                .addComponent(btnActualizarPaciente_Admin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnConsultarPaciente_Admin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnConsultarHorario_Admin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(39, 39, 39))))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 710, 310));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultarPaciente_AdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarPaciente_AdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultarPaciente_AdminActionPerformed

    private void btnActualizarPaciente_AdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarPaciente_AdminMouseClicked
        Actualizar_PacienteAdmin updatePacienteAdmin = new Actualizar_PacienteAdmin();
        updatePacienteAdmin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnActualizarPaciente_AdminMouseClicked

    private void btnActualizarPaciente_AdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarPaciente_AdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnActualizarPaciente_AdminActionPerformed

    private void btnInsertarHorario_AdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInsertarHorario_AdminMouseClicked
        Registro_HorarioAdmin insertHorarioAdmin = new Registro_HorarioAdmin();
        insertHorarioAdmin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnInsertarHorario_AdminMouseClicked

    private void btnBorrarHorario_AdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBorrarHorario_AdminMouseClicked
        Eliminar_HorarioAdmin deleteHorarioAdmin = new Eliminar_HorarioAdmin();
        deleteHorarioAdmin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBorrarHorario_AdminMouseClicked

    private void btnBorrarHorario_AdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarHorario_AdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBorrarHorario_AdminActionPerformed

    private void btnActualizarHorario_AdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarHorario_AdminMouseClicked
        Actualizar_HorarioAdmin updateHorarioAdmin = new Actualizar_HorarioAdmin();
        updateHorarioAdmin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnActualizarHorario_AdminMouseClicked

    private void btnActualizarHorario_AdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarHorario_AdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnActualizarHorario_AdminActionPerformed

    private void btnConsultarHorario_AdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarHorario_AdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultarHorario_AdminActionPerformed

    private void btnBorrarDoctor_AdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarDoctor_AdminActionPerformed
        // TODO add your handling code here:
        Eliminar_DoctorAdmin deleteDoctorAdmin =  new Eliminar_DoctorAdmin();
        deleteDoctorAdmin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBorrarDoctor_AdminActionPerformed

    private void btnActualizarDoctor_AdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarDoctor_AdminActionPerformed
        // TODO add your handling code here:
        Actualizar_DoctorAdmin updateDoctorAdmin = new Actualizar_DoctorAdmin();
        updateDoctorAdmin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnActualizarDoctor_AdminActionPerformed

    private void btnConsultarDoctor_AdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarDoctor_AdminActionPerformed
        // TODO add your handling code here:
        Consultar_DoctorAdmin selectDoctorAdmin = new Consultar_DoctorAdmin();
        selectDoctorAdmin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnConsultarDoctor_AdminActionPerformed

    private void btnBorrarConsultorio_AdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarConsultorio_AdminActionPerformed
        // TODO add your handling code here:
        Eliminar_ConsultorioA deleteConsultorio = new Eliminar_ConsultorioA();
        deleteConsultorio.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBorrarConsultorio_AdminActionPerformed

    private void btnActualizarConsultorio_AdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarConsultorio_AdminActionPerformed
        // TODO add your handling code here:
        Actualizar_ConsultorioA updateConsultorio = new Actualizar_ConsultorioA();
        updateConsultorio.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnActualizarConsultorio_AdminActionPerformed

    private void btnConsultarConsultorio_AdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarConsultorio_AdminActionPerformed
        // TODO add your handling code here:
        Consultar_ConsultorioA selectConsultorio = new Consultar_ConsultorioA();
        selectConsultorio.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnConsultarConsultorio_AdminActionPerformed

    private void btnInsertarDoctor_AdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInsertarDoctor_AdminMouseClicked
        //INSERTAR DOCTOR DENTRO DE LA TABLA RECEPCIONISTA
        Registro_DoctorAdmin insertDoctorAdmin = new Registro_DoctorAdmin();
        insertDoctorAdmin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnInsertarDoctor_AdminMouseClicked

    private void btnInsertarDoctor_AdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarDoctor_AdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInsertarDoctor_AdminActionPerformed

    private void btnBorrarPaciente_AdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBorrarPaciente_AdminMouseClicked
        Eliminar_PacienteAdmin deletePacienteAdmin = new Eliminar_PacienteAdmin();
        deletePacienteAdmin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBorrarPaciente_AdminMouseClicked

    private void btnBorrarPaciente_AdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarPaciente_AdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBorrarPaciente_AdminActionPerformed

    private void btnInsertarPaciente_AdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInsertarPaciente_AdminMouseClicked
        Registro_PacienteAdmin insertPacienteAdmin = new Registro_PacienteAdmin();
        insertPacienteAdmin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnInsertarPaciente_AdminMouseClicked

    private void btnInsertarPaciente_AdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarPaciente_AdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInsertarPaciente_AdminActionPerformed

    private void btnConsultarPaciente_AdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultarPaciente_AdminMouseClicked
        // TODO add your handling code here:
        Consultar_PacienteAdmin selectPacienteAdmin = new Consultar_PacienteAdmin();
        selectPacienteAdmin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnConsultarPaciente_AdminMouseClicked

    private void btnInsertarHorario_AdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarHorario_AdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInsertarHorario_AdminActionPerformed

    private void btnConsultarHorario_AdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultarHorario_AdminMouseClicked
        // TODO add your handling code here:
        Consultar_HorarioAdmin selectHorarioAdmin = new Consultar_HorarioAdmin();
        selectHorarioAdmin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnConsultarHorario_AdminMouseClicked

    private void btnInsertarConsultorio_AdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarConsultorio_AdminActionPerformed
        Registro_ConsultorioA insertPacienteAdmin = new Registro_ConsultorioA();
        insertPacienteAdmin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnInsertarConsultorio_AdminActionPerformed

    private void btnRegistrarPacienteTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarPacienteTMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarPacienteTMouseClicked

    private void btnRegistrarPacienteTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarPacienteTActionPerformed
        Transacciones transacciones = new Transacciones();
        transacciones.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegistrarPacienteTActionPerformed

    private void btnInsertarConsultorioRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarConsultorioRActionPerformed
        Login_BD login = new Login_BD();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnInsertarConsultorioRActionPerformed

    private void btnPerfilAdministradorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPerfilAdministradorMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPerfilAdministradorMouseClicked

    private void btnPerfilAdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerfilAdministradorActionPerformed
        ViewPerfilesA perfil = new ViewPerfilesA();
        perfil.consultarUsuario("4");
        perfil.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPerfilAdministradorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal_Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal_Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal_Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal_Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal_Administrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Encabezado;
    private javax.swing.JPanel OpcionestablaDoctor;
    private javax.swing.JButton btnActualizarConsultorio_Admin;
    private javax.swing.JButton btnActualizarDoctor_Admin;
    private javax.swing.JButton btnActualizarHorario_Admin;
    private javax.swing.JButton btnActualizarPaciente_Admin;
    private javax.swing.JButton btnBorrarConsultorio_Admin;
    private javax.swing.JButton btnBorrarDoctor_Admin;
    private javax.swing.JButton btnBorrarHorario_Admin;
    private javax.swing.JButton btnBorrarPaciente_Admin;
    private javax.swing.JButton btnConsultarConsultorio_Admin;
    private javax.swing.JButton btnConsultarDoctor_Admin;
    private javax.swing.JButton btnConsultarHorario_Admin;
    private javax.swing.JButton btnConsultarPaciente_Admin;
    private javax.swing.JButton btnInsertarConsultorioR;
    private javax.swing.JButton btnInsertarConsultorio_Admin;
    private javax.swing.JButton btnInsertarDoctor_Admin;
    private javax.swing.JButton btnInsertarHorario_Admin;
    private javax.swing.JButton btnInsertarPaciente_Admin;
    private javax.swing.JButton btnPerfilAdministrador;
    private javax.swing.JButton btnRegistrarPacienteT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
