/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;

/**
 *
 * @author sandybau
 */
public class Principal_Doctor extends javax.swing.JFrame {

    /**
     * Creates new form Principal_Doctor
     */
    public Principal_Doctor() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Encabezado = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        OpcionestablaDoctor = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnInsertarConsultorioR = new javax.swing.JButton();
        btnPerfilDoctor = new javax.swing.JButton();
        OpcionestablaDoctor1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnConsultarPaciente_Doctor = new javax.swing.JButton();
        btnActualizarPaciente_Doctor = new javax.swing.JButton();
        btnActualizarHorario_Doctor = new javax.swing.JButton();
        btnConsultarHorario_Doctor = new javax.swing.JButton();
        btnActualizarDoctor_Doctor = new javax.swing.JButton();
        btnConsultarDoctor_Doctor = new javax.swing.JButton();
        btnActualizarConsultorio_Doctor = new javax.swing.JButton();
        btnConsultarConsultorio_Doctor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Encabezado.setBackground(new java.awt.Color(255, 255, 153));

        jLabel1.setBackground(new java.awt.Color(0, 102, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("DOCTOR");

        OpcionestablaDoctor.setBackground(new java.awt.Color(0, 153, 153));
        OpcionestablaDoctor.setForeground(new java.awt.Color(0, 153, 153));

        jLabel2.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("DOCTOR");

        jLabel3.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("PACIENTE");

        jLabel4.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("CONSULTORIO");

        jLabel5.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("HORARIO");

        javax.swing.GroupLayout OpcionestablaDoctorLayout = new javax.swing.GroupLayout(OpcionestablaDoctor);
        OpcionestablaDoctor.setLayout(OpcionestablaDoctorLayout);
        OpcionestablaDoctorLayout.setHorizontalGroup(
            OpcionestablaDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OpcionestablaDoctorLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(jLabel4)
                .addGap(37, 37, 37))
        );
        OpcionestablaDoctorLayout.setVerticalGroup(
            OpcionestablaDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OpcionestablaDoctorLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(OpcionestablaDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(15, 15, 15))
        );

        btnInsertarConsultorioR.setBackground(new java.awt.Color(255, 0, 51));
        btnInsertarConsultorioR.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnInsertarConsultorioR.setForeground(new java.awt.Color(255, 255, 255));
        btnInsertarConsultorioR.setText("LOGIN");
        btnInsertarConsultorioR.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnInsertarConsultorioR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarConsultorioRActionPerformed(evt);
            }
        });

        btnPerfilDoctor.setBackground(new java.awt.Color(255, 204, 102));
        btnPerfilDoctor.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnPerfilDoctor.setForeground(new java.awt.Color(0, 51, 51));
        btnPerfilDoctor.setText("PERFIL");
        btnPerfilDoctor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPerfilDoctor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPerfilDoctorMouseClicked(evt);
            }
        });
        btnPerfilDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerfilDoctorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout EncabezadoLayout = new javax.swing.GroupLayout(Encabezado);
        Encabezado.setLayout(EncabezadoLayout);
        EncabezadoLayout.setHorizontalGroup(
            EncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EncabezadoLayout.createSequentialGroup()
                .addComponent(OpcionestablaDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(EncabezadoLayout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addComponent(jLabel1)
                .addGap(125, 125, 125)
                .addComponent(btnInsertarConsultorioR, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPerfilDoctor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(42, 42, 42))
        );
        EncabezadoLayout.setVerticalGroup(
            EncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EncabezadoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(EncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInsertarConsultorioR, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPerfilDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(OpcionestablaDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(Encabezado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 70));

        OpcionestablaDoctor1.setBackground(new java.awt.Color(0, 153, 153));
        OpcionestablaDoctor1.setForeground(new java.awt.Color(0, 153, 153));

        jLabel6.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("DOCTOR");

        jLabel7.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("PACIENTE");

        jLabel8.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("CONSULTORIO");

        jLabel9.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("HORARIO");

        javax.swing.GroupLayout OpcionestablaDoctor1Layout = new javax.swing.GroupLayout(OpcionestablaDoctor1);
        OpcionestablaDoctor1.setLayout(OpcionestablaDoctor1Layout);
        OpcionestablaDoctor1Layout.setHorizontalGroup(
            OpcionestablaDoctor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OpcionestablaDoctor1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(jLabel8)
                .addGap(37, 37, 37))
        );
        OpcionestablaDoctor1Layout.setVerticalGroup(
            OpcionestablaDoctor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OpcionestablaDoctor1Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(OpcionestablaDoctor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(15, 15, 15))
        );

        jPanel1.add(OpcionestablaDoctor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 710, 70));

        jPanel4.setBackground(new java.awt.Color(153, 204, 255));

        btnConsultarPaciente_Doctor.setBackground(new java.awt.Color(153, 255, 153));
        btnConsultarPaciente_Doctor.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnConsultarPaciente_Doctor.setForeground(new java.awt.Color(0, 51, 51));
        btnConsultarPaciente_Doctor.setText("CONSULTAR");
        btnConsultarPaciente_Doctor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnConsultarPaciente_Doctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarPaciente_DoctorActionPerformed(evt);
            }
        });

        btnActualizarPaciente_Doctor.setBackground(new java.awt.Color(153, 255, 153));
        btnActualizarPaciente_Doctor.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnActualizarPaciente_Doctor.setForeground(new java.awt.Color(0, 51, 51));
        btnActualizarPaciente_Doctor.setText("ACTUALIZAR");
        btnActualizarPaciente_Doctor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnActualizarPaciente_Doctor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnActualizarPaciente_DoctorMouseClicked(evt);
            }
        });
        btnActualizarPaciente_Doctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarPaciente_DoctorActionPerformed(evt);
            }
        });

        btnActualizarHorario_Doctor.setBackground(new java.awt.Color(255, 204, 102));
        btnActualizarHorario_Doctor.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnActualizarHorario_Doctor.setForeground(new java.awt.Color(0, 51, 51));
        btnActualizarHorario_Doctor.setText("ACTUALIZAR");
        btnActualizarHorario_Doctor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnActualizarHorario_Doctor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnActualizarHorario_DoctorMouseClicked(evt);
            }
        });
        btnActualizarHorario_Doctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarHorario_DoctorActionPerformed(evt);
            }
        });

        btnConsultarHorario_Doctor.setBackground(new java.awt.Color(255, 204, 102));
        btnConsultarHorario_Doctor.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnConsultarHorario_Doctor.setForeground(new java.awt.Color(0, 51, 51));
        btnConsultarHorario_Doctor.setText("CONSULTAR");
        btnConsultarHorario_Doctor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnConsultarHorario_Doctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarHorario_DoctorActionPerformed(evt);
            }
        });

        btnActualizarDoctor_Doctor.setBackground(new java.awt.Color(153, 255, 153));
        btnActualizarDoctor_Doctor.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnActualizarDoctor_Doctor.setForeground(new java.awt.Color(0, 51, 51));
        btnActualizarDoctor_Doctor.setText("ACTUALIZAR");
        btnActualizarDoctor_Doctor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnActualizarDoctor_Doctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarDoctor_DoctorActionPerformed(evt);
            }
        });

        btnConsultarDoctor_Doctor.setBackground(new java.awt.Color(153, 255, 153));
        btnConsultarDoctor_Doctor.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnConsultarDoctor_Doctor.setForeground(new java.awt.Color(0, 51, 51));
        btnConsultarDoctor_Doctor.setText("CONSULTAR");
        btnConsultarDoctor_Doctor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnConsultarDoctor_Doctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarDoctor_DoctorActionPerformed(evt);
            }
        });

        btnActualizarConsultorio_Doctor.setBackground(new java.awt.Color(255, 204, 102));
        btnActualizarConsultorio_Doctor.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnActualizarConsultorio_Doctor.setForeground(new java.awt.Color(0, 51, 51));
        btnActualizarConsultorio_Doctor.setText("ACTUALIZAR");
        btnActualizarConsultorio_Doctor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnActualizarConsultorio_Doctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarConsultorio_DoctorActionPerformed(evt);
            }
        });

        btnConsultarConsultorio_Doctor.setBackground(new java.awt.Color(255, 204, 102));
        btnConsultarConsultorio_Doctor.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnConsultarConsultorio_Doctor.setForeground(new java.awt.Color(0, 51, 51));
        btnConsultarConsultorio_Doctor.setText("CONSULTAR");
        btnConsultarConsultorio_Doctor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnConsultarConsultorio_Doctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarConsultorio_DoctorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnConsultarPaciente_Doctor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnActualizarPaciente_Doctor, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE))
                .addGap(67, 67, 67)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnConsultarHorario_Doctor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnActualizarHorario_Doctor, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnConsultarDoctor_Doctor, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                        .addComponent(btnConsultarConsultorio_Doctor, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnActualizarDoctor_Doctor, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnActualizarConsultorio_Doctor, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizarPaciente_Doctor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActualizarHorario_Doctor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActualizarDoctor_Doctor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActualizarConsultorio_Doctor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConsultarPaciente_Doctor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultarHorario_Doctor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultarDoctor_Doctor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultarConsultorio_Doctor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 710, 180));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultarPaciente_DoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarPaciente_DoctorActionPerformed
        Consultar_PacienteD selectPaciente = new Consultar_PacienteD();
        selectPaciente.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnConsultarPaciente_DoctorActionPerformed

    private void btnActualizarPaciente_DoctorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarPaciente_DoctorMouseClicked
        Actualizar_PacienteD updatePaciente = new Actualizar_PacienteD();
        updatePaciente.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnActualizarPaciente_DoctorMouseClicked

    private void btnActualizarPaciente_DoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarPaciente_DoctorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnActualizarPaciente_DoctorActionPerformed

    private void btnActualizarHorario_DoctorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarHorario_DoctorMouseClicked
        Actualizar_HorarioD updateHorario = new Actualizar_HorarioD();
        updateHorario.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnActualizarHorario_DoctorMouseClicked

    private void btnActualizarHorario_DoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarHorario_DoctorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnActualizarHorario_DoctorActionPerformed

    private void btnConsultarHorario_DoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarHorario_DoctorActionPerformed
        Consultar_HorarioD selectHorario = new Consultar_HorarioD();
        selectHorario.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnConsultarHorario_DoctorActionPerformed

    private void btnActualizarDoctor_DoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarDoctor_DoctorActionPerformed
        Actualizar_DoctorD updateDoctor = new Actualizar_DoctorD();
        updateDoctor.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnActualizarDoctor_DoctorActionPerformed

    private void btnConsultarDoctor_DoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarDoctor_DoctorActionPerformed
        Consultar_DoctorD selectDoctor = new Consultar_DoctorD();
        selectDoctor.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnConsultarDoctor_DoctorActionPerformed

    private void btnActualizarConsultorio_DoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarConsultorio_DoctorActionPerformed
        // TODO add your handling code here:
        Actualizar_ConsultorioD updateConsultorio = new  Actualizar_ConsultorioD ();
        updateConsultorio.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnActualizarConsultorio_DoctorActionPerformed

    private void btnConsultarConsultorio_DoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarConsultorio_DoctorActionPerformed
        // TODO add your handling code here:
        Consultar_ConsultorioD selectConsultorio = new Consultar_ConsultorioD();
        selectConsultorio.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnConsultarConsultorio_DoctorActionPerformed

    private void btnInsertarConsultorioRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarConsultorioRActionPerformed
        Login_BD login = new Login_BD();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnInsertarConsultorioRActionPerformed

    private void btnPerfilDoctorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPerfilDoctorMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPerfilDoctorMouseClicked

    private void btnPerfilDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerfilDoctorActionPerformed
        ViewPerfilesD perfil = new ViewPerfilesD();
        perfil.consultarUsuario("3");
        perfil.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPerfilDoctorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal_Doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal_Doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal_Doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal_Doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal_Doctor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Encabezado;
    private javax.swing.JPanel OpcionestablaDoctor;
    private javax.swing.JPanel OpcionestablaDoctor1;
    private javax.swing.JButton btnActualizarConsultorio_Doctor;
    private javax.swing.JButton btnActualizarDoctor_Doctor;
    private javax.swing.JButton btnActualizarHorario_Doctor;
    private javax.swing.JButton btnActualizarPaciente_Doctor;
    private javax.swing.JButton btnConsultarConsultorio_Doctor;
    private javax.swing.JButton btnConsultarDoctor_Doctor;
    private javax.swing.JButton btnConsultarHorario_Doctor;
    private javax.swing.JButton btnConsultarPaciente_Doctor;
    private javax.swing.JButton btnInsertarConsultorioR;
    private javax.swing.JButton btnPerfilDoctor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
