/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;

/**
 *
 * @author Lizeth
 */
public class PrincipalPaciente extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalPaciente
     */
    public PrincipalPaciente() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnConsultarPacienteR = new javax.swing.JButton();
        btnConsultarHorarioR = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnInsertarConsultorioR = new javax.swing.JButton();
        btnPerfilPaciente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(0, 153, 153));
        jPanel5.setForeground(new java.awt.Color(0, 153, 153));

        jLabel3.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("PACIENTE");

        jLabel5.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("HORARIO");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(304, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 710, 70));

        btnConsultarPacienteR.setBackground(new java.awt.Color(153, 255, 153));
        btnConsultarPacienteR.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnConsultarPacienteR.setForeground(new java.awt.Color(0, 51, 51));
        btnConsultarPacienteR.setText("CONSULTAR");
        btnConsultarPacienteR.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnConsultarPacienteR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarPacienteRActionPerformed(evt);
            }
        });
        jPanel1.add(btnConsultarPacienteR, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, -1, -1));

        btnConsultarHorarioR.setBackground(new java.awt.Color(255, 204, 102));
        btnConsultarHorarioR.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnConsultarHorarioR.setForeground(new java.awt.Color(0, 51, 51));
        btnConsultarHorarioR.setText("CONSULTAR");
        btnConsultarHorarioR.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnConsultarHorarioR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarHorarioRActionPerformed(evt);
            }
        });
        jPanel1.add(btnConsultarHorarioR, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, -1, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 153));

        jLabel1.setBackground(new java.awt.Color(0, 102, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("PACIENTE");

        btnInsertarConsultorioR.setBackground(new java.awt.Color(255, 0, 51));
        btnInsertarConsultorioR.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnInsertarConsultorioR.setForeground(new java.awt.Color(255, 255, 255));
        btnInsertarConsultorioR.setText("LOGIN");
        btnInsertarConsultorioR.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnInsertarConsultorioR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarConsultorioRActionPerformed(evt);
            }
        });

        btnPerfilPaciente.setBackground(new java.awt.Color(255, 204, 102));
        btnPerfilPaciente.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnPerfilPaciente.setForeground(new java.awt.Color(0, 51, 51));
        btnPerfilPaciente.setText("PERFIL");
        btnPerfilPaciente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPerfilPaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPerfilPacienteMouseClicked(evt);
            }
        });
        btnPerfilPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerfilPacienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addComponent(btnInsertarConsultorioR, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPerfilPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(201, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInsertarConsultorioR)
                    .addComponent(btnPerfilPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 20, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultarPacienteRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarPacienteRActionPerformed
        Consultar_PacienteP selectPaciente = new Consultar_PacienteP();
        selectPaciente.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnConsultarPacienteRActionPerformed

    private void btnConsultarHorarioRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarHorarioRActionPerformed
        Consultar_HorarioP selectPaciente = new Consultar_HorarioP();
        selectPaciente.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnConsultarHorarioRActionPerformed

    private void btnInsertarConsultorioRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarConsultorioRActionPerformed
        Login_BD login = new Login_BD();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnInsertarConsultorioRActionPerformed

    private void btnPerfilPacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPerfilPacienteMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPerfilPacienteMouseClicked

    private void btnPerfilPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerfilPacienteActionPerformed
        ViewPerfilesP perfil = new ViewPerfilesP();
        perfil.consultarUsuario("2");
        perfil.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPerfilPacienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalPaciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultarHorarioR;
    private javax.swing.JButton btnConsultarPacienteR;
    private javax.swing.JButton btnInsertarConsultorioR;
    private javax.swing.JButton btnPerfilPaciente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
