/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;

import Clases.Conectar;
import java.sql.Connection;
import javax.swing.JOptionPane;
/**
 *
 * @author rafae
 */
public class Registro_DoctorT extends javax.swing.JFrame {
    Conectar conectarBD = new Conectar();
    /**
     * Creates new form Registro_DoctorT
     */
    public Registro_DoctorT() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        background = new javax.swing.JPanel();
        Encabezado = new javax.swing.JPanel();
        Nombre_Encabezado = new javax.swing.JLabel();
        Nombre_Doctor = new javax.swing.JLabel();
        Apellido_Paterno = new javax.swing.JLabel();
        Apellido_Materno = new javax.swing.JLabel();
        Id_Doctor = new javax.swing.JLabel();
        txtEspecialidadG = new javax.swing.JLabel();
        txtApellidoPaternoDoctor = new javax.swing.JTextField();
        txtIdDoctor = new javax.swing.JTextField();
        txtNombreDoctor = new javax.swing.JTextField();
        txtEspecialidadDoctor = new javax.swing.JTextField();
        txtApellidoMaternoDoctor = new javax.swing.JTextField();
        btnRegresarDoctor = new javax.swing.JButton();
        btnRegistrarDoctorT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        background.setBackground(new java.awt.Color(153, 204, 255));

        Encabezado.setBackground(new java.awt.Color(0, 153, 255));

        Nombre_Encabezado.setFont(new java.awt.Font("Segoe UI Black", 0, 20)); // NOI18N
        Nombre_Encabezado.setForeground(new java.awt.Color(255, 255, 255));
        Nombre_Encabezado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Nombre_Encabezado.setText("REGISTRO DOCTORES");

        javax.swing.GroupLayout EncabezadoLayout = new javax.swing.GroupLayout(Encabezado);
        Encabezado.setLayout(EncabezadoLayout);
        EncabezadoLayout.setHorizontalGroup(
            EncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EncabezadoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Nombre_Encabezado)
                .addGap(226, 226, 226))
        );
        EncabezadoLayout.setVerticalGroup(
            EncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EncabezadoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Nombre_Encabezado, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        Nombre_Doctor.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        Nombre_Doctor.setForeground(new java.awt.Color(0, 51, 51));
        Nombre_Doctor.setText("NOMBRE DEL DOCTOR");

        Apellido_Paterno.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        Apellido_Paterno.setForeground(new java.awt.Color(0, 51, 51));
        Apellido_Paterno.setText("APELLIDO PATERNO");

        Apellido_Materno.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        Apellido_Materno.setForeground(new java.awt.Color(0, 51, 51));
        Apellido_Materno.setText("APELLIDO MATERNO");

        Id_Doctor.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        Id_Doctor.setForeground(new java.awt.Color(0, 51, 51));
        Id_Doctor.setText("NÚMERO DE IDENTIFICACIÓN (10)");

        txtEspecialidadG.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        txtEspecialidadG.setForeground(new java.awt.Color(0, 51, 51));
        txtEspecialidadG.setText("ESPECIALIDAD");

        txtApellidoPaternoDoctor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtApellidoPaternoDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoPaternoDoctorActionPerformed(evt);
            }
        });

        txtIdDoctor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtIdDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdDoctorActionPerformed(evt);
            }
        });

        txtNombreDoctor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtNombreDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreDoctorActionPerformed(evt);
            }
        });

        txtEspecialidadDoctor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtEspecialidadDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEspecialidadDoctorActionPerformed(evt);
            }
        });

        txtApellidoMaternoDoctor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtApellidoMaternoDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoMaternoDoctorActionPerformed(evt);
            }
        });

        btnRegresarDoctor.setBackground(new java.awt.Color(0, 153, 255));
        btnRegresarDoctor.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnRegresarDoctor.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresarDoctor.setText("REGRESAR");
        btnRegresarDoctor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegresarDoctorMouseClicked(evt);
            }
        });
        btnRegresarDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarDoctorActionPerformed(evt);
            }
        });

        btnRegistrarDoctorT.setBackground(new java.awt.Color(0, 153, 255));
        btnRegistrarDoctorT.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnRegistrarDoctorT.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarDoctorT.setText("FINALIZAR");
        btnRegistrarDoctorT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarDoctorTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Encabezado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Apellido_Materno)
                            .addComponent(txtEspecialidadG)
                            .addGroup(backgroundLayout.createSequentialGroup()
                                .addComponent(Id_Doctor)
                                .addGap(22, 22, 22)
                                .addComponent(txtIdDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                        .addComponent(btnRegresarDoctor)
                        .addGap(26, 26, 26))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, backgroundLayout.createSequentialGroup()
                                .addComponent(Nombre_Doctor, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(93, 93, 93)
                                .addComponent(txtNombreDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, backgroundLayout.createSequentialGroup()
                                .addComponent(Apellido_Paterno)
                                .addGap(119, 119, 119)
                                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtApellidoMaternoDoctor)
                                    .addComponent(txtApellidoPaternoDoctor)
                                    .addComponent(txtEspecialidadDoctor))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                    .addContainerGap(601, Short.MAX_VALUE)
                    .addComponent(btnRegistrarDoctorT)
                    .addGap(23, 23, 23)))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(Encabezado, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nombre_Doctor)
                    .addComponent(txtNombreDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Apellido_Paterno)
                    .addComponent(txtApellidoPaternoDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Apellido_Materno)
                    .addComponent(txtApellidoMaternoDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Id_Doctor)
                            .addComponent(txtIdDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRegresarDoctor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEspecialidadG)
                    .addComponent(txtEspecialidadDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
            .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                    .addContainerGap(341, Short.MAX_VALUE)
                    .addComponent(btnRegistrarDoctorT)
                    .addGap(27, 27, 27)))
        );

        jPanel1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 734, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void limpiarCajas(){
        txtNombreDoctor.setText(null);
        txtApellidoPaternoDoctor.setText(null);
        txtApellidoMaternoDoctor.setText(null);
        txtIdDoctor.setText(null);
        txtEspecialidadDoctor.setText(null);
    }
    
    private void txtApellidoPaternoDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoPaternoDoctorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoPaternoDoctorActionPerformed

    private void txtIdDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdDoctorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdDoctorActionPerformed

    private void txtNombreDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreDoctorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreDoctorActionPerformed

    private void txtEspecialidadDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEspecialidadDoctorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEspecialidadDoctorActionPerformed

    private void txtApellidoMaternoDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoMaternoDoctorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoMaternoDoctorActionPerformed

    private void btnRegresarDoctorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarDoctorMouseClicked
        Transacciones nuevaV = new Transacciones();
        nuevaV.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarDoctorMouseClicked

    private void btnRegresarDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarDoctorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegresarDoctorActionPerformed

    private void btnRegistrarDoctorTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarDoctorTActionPerformed
        Connection con = null;
        try {
            con = conectarBD.getConnection();
            conectarBD.ps = con.prepareStatement("INSERT INTO doctor (Nombre_Doctor, Apellido_Paterno_Doctor, Apellido_Materno_Doctor, Id_Doctor, Especialidad) VALUES (?, ?, ?, ?, ?)");
            conectarBD.ps.setString(1, txtNombreDoctor.getText());
            conectarBD.ps.setString(2, txtApellidoPaternoDoctor.getText());
            conectarBD.ps.setString(3, txtApellidoMaternoDoctor.getText());
            conectarBD.ps.setString(4, txtIdDoctor.getText());
            conectarBD.ps.setString(5, txtEspecialidadDoctor.getText());

            //EJECUTAR LA CONSULTA
            int res = conectarBD.ps.executeUpdate();
            if(res > 0){
                JOptionPane.showMessageDialog(null, "TRANSACCIÓN EXITOSA");
                limpiarCajas();
            }
            else{
                JOptionPane.showMessageDialog(null, "ERROR AL EJECUTAR TRANSACCIÓN");
                limpiarCajas();
            }
            //CERRAR BD
            con.close();
        } catch (Exception e) {
            System.out.println("Error: "+e);
        }
    }//GEN-LAST:event_btnRegistrarDoctorTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro_DoctorT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro_DoctorT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro_DoctorT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro_DoctorT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro_DoctorT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Apellido_Materno;
    private javax.swing.JLabel Apellido_Paterno;
    private javax.swing.JPanel Encabezado;
    private javax.swing.JLabel Id_Doctor;
    private javax.swing.JLabel Nombre_Doctor;
    private javax.swing.JLabel Nombre_Encabezado;
    private javax.swing.JPanel background;
    private javax.swing.JButton btnRegistrarDoctorT;
    private javax.swing.JButton btnRegresarDoctor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtApellidoMaternoDoctor;
    private javax.swing.JTextField txtApellidoPaternoDoctor;
    private javax.swing.JTextField txtEspecialidadDoctor;
    private javax.swing.JLabel txtEspecialidadG;
    private javax.swing.JTextField txtIdDoctor;
    private javax.swing.JTextField txtNombreDoctor;
    // End of variables declaration//GEN-END:variables
}
