/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;

import Clases.Conectar;
import java.sql.Connection;
import javax.swing.JOptionPane;
/**
 *
 * @author rafae
 */
public class Registro_ConsultorioR extends javax.swing.JFrame {
    Conectar conectarBD = new Conectar();
    /**
     * Creates new form Registro_ConsultorioR
     */
    public Registro_ConsultorioR() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Encabezado = new javax.swing.JPanel();
        Nombre_Encabezado = new javax.swing.JLabel();
        Cuerpo = new javax.swing.JPanel();
        IdDoctor = new javax.swing.JLabel();
        IdConsultorio = new javax.swing.JLabel();
        txtIdDoctor = new javax.swing.JTextField();
        txtIdConsultorio = new javax.swing.JTextField();
        btnRegresarConsultorio = new javax.swing.JButton();
        btnRegistrarConsultorio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Encabezado.setBackground(new java.awt.Color(0, 153, 255));

        Nombre_Encabezado.setFont(new java.awt.Font("Segoe UI Black", 0, 20)); // NOI18N
        Nombre_Encabezado.setForeground(new java.awt.Color(255, 255, 255));
        Nombre_Encabezado.setText("REGISTRO CONSULTORIO");

        javax.swing.GroupLayout EncabezadoLayout = new javax.swing.GroupLayout(Encabezado);
        Encabezado.setLayout(EncabezadoLayout);
        EncabezadoLayout.setHorizontalGroup(
            EncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EncabezadoLayout.createSequentialGroup()
                .addContainerGap(226, Short.MAX_VALUE)
                .addComponent(Nombre_Encabezado)
                .addGap(213, 213, 213))
        );
        EncabezadoLayout.setVerticalGroup(
            EncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EncabezadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Nombre_Encabezado)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel1.add(Encabezado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 60));

        Cuerpo.setBackground(new java.awt.Color(153, 204, 255));

        IdDoctor.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        IdDoctor.setForeground(new java.awt.Color(0, 51, 51));
        IdDoctor.setText("ID DOCTOR (10)");

        IdConsultorio.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        IdConsultorio.setForeground(new java.awt.Color(0, 51, 51));
        IdConsultorio.setText("ID CONSULTORIO (5)");

        txtIdDoctor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtIdDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdDoctorActionPerformed(evt);
            }
        });

        txtIdConsultorio.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtIdConsultorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdConsultorioActionPerformed(evt);
            }
        });

        btnRegresarConsultorio.setBackground(new java.awt.Color(0, 153, 255));
        btnRegresarConsultorio.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnRegresarConsultorio.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresarConsultorio.setText("REGRESAR");
        btnRegresarConsultorio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegresarConsultorioMouseClicked(evt);
            }
        });
        btnRegresarConsultorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarConsultorioActionPerformed(evt);
            }
        });

        btnRegistrarConsultorio.setBackground(new java.awt.Color(0, 153, 255));
        btnRegistrarConsultorio.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnRegistrarConsultorio.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarConsultorio.setText("REGISTRAR");
        btnRegistrarConsultorio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistrarConsultorioMouseClicked(evt);
            }
        });
        btnRegistrarConsultorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarConsultorioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CuerpoLayout = new javax.swing.GroupLayout(Cuerpo);
        Cuerpo.setLayout(CuerpoLayout);
        CuerpoLayout.setHorizontalGroup(
            CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CuerpoLayout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addGroup(CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(CuerpoLayout.createSequentialGroup()
                        .addComponent(btnRegistrarConsultorio, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(208, 208, 208)
                        .addComponent(btnRegresarConsultorio, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CuerpoLayout.createSequentialGroup()
                        .addGroup(CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(IdDoctor)
                            .addComponent(IdConsultorio))
                        .addGap(50, 50, 50)
                        .addGroup(CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtIdDoctor, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                            .addComponent(txtIdConsultorio))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        CuerpoLayout.setVerticalGroup(
            CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CuerpoLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IdDoctor)
                    .addComponent(txtIdDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IdConsultorio)
                    .addComponent(txtIdConsultorio, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegresarConsultorio)
                    .addComponent(btnRegistrarConsultorio))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jPanel1.add(Cuerpo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 690, 240));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void limpiarCajas(){
        txtIdDoctor.setText(null);
        txtIdConsultorio.setText(null);
    }
    private void txtIdDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdDoctorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdDoctorActionPerformed

    private void txtIdConsultorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdConsultorioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdConsultorioActionPerformed

    private void btnRegresarConsultorioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarConsultorioMouseClicked
        PrincipalRecepcionista nuevaV = new PrincipalRecepcionista();
        nuevaV.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarConsultorioMouseClicked

    private void btnRegresarConsultorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarConsultorioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegresarConsultorioActionPerformed

    private void btnRegistrarConsultorioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarConsultorioMouseClicked
        // TODO add your handling code here:
        // ESTA MOFICICACIÓN FUE REALIZADA POR EMMANUEL JAIR BRAVO GARCIA
        Connection  con = null;
        try{
            con = conectarBD.getConnection();
            conectarBD.ps = con.prepareStatement("INSERT INTO consultorio (Id_Doctor, Id_Consultorio) VALUES (?,?)");
            conectarBD.ps.setString(1,txtIdDoctor.getText());
            conectarBD.ps.setString(2,txtIdConsultorio.getText());

            //EJECUTAR LA CONSULTA
            int res = conectarBD.ps.executeUpdate();
            if(res > 0){
                JOptionPane.showMessageDialog(null, "CONSULTORIO GUARDADO");
                limpiarCajas();
            }
            else{
                JOptionPane.showMessageDialog(null, "ERROR AL GUARDAR CONSULTORIO");
                limpiarCajas();
            }

            con.close();

        }catch(Exception e){
            System.err.println(e);
        }
    }//GEN-LAST:event_btnRegistrarConsultorioMouseClicked

    private void btnRegistrarConsultorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarConsultorioActionPerformed

    }//GEN-LAST:event_btnRegistrarConsultorioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro_ConsultorioR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro_ConsultorioR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro_ConsultorioR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro_ConsultorioR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro_ConsultorioR().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Cuerpo;
    private javax.swing.JPanel Encabezado;
    private javax.swing.JLabel IdConsultorio;
    private javax.swing.JLabel IdDoctor;
    private javax.swing.JLabel Nombre_Encabezado;
    private javax.swing.JButton btnRegistrarConsultorio;
    private javax.swing.JButton btnRegresarConsultorio;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtIdConsultorio;
    private javax.swing.JTextField txtIdDoctor;
    // End of variables declaration//GEN-END:variables
}
