/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;
import Clases.Conectar;
import java.sql.Connection;
import javax.swing.JOptionPane;
/**
 *
 * @author sandybau
 */
public class Registro_HorarioAdmin extends javax.swing.JFrame {
    Conectar conectarBD = new Conectar();
    /**
     * Creates new form Registro_HorarioAdmin
     */
    public Registro_HorarioAdmin() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        Encabezado = new javax.swing.JPanel();
        Nombre_Encabezado = new javax.swing.JLabel();
        Cuerpo = new javax.swing.JPanel();
        Apellido_Paterno = new javax.swing.JLabel();
        CURP = new javax.swing.JLabel();
        Telefono = new javax.swing.JLabel();
        txtCitaHorarioR = new javax.swing.JTextField();
        txtCurpHorarioR = new javax.swing.JTextField();
        txtIdDoctorHorarioR = new javax.swing.JTextField();
        btnRegistrarHorario = new javax.swing.JButton();
        btnRegresarHorario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Encabezado.setBackground(new java.awt.Color(0, 153, 255));

        Nombre_Encabezado.setFont(new java.awt.Font("Segoe UI Black", 0, 20)); // NOI18N
        Nombre_Encabezado.setForeground(new java.awt.Color(255, 255, 255));
        Nombre_Encabezado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Nombre_Encabezado.setText("REGISTRO HORARIO");

        javax.swing.GroupLayout EncabezadoLayout = new javax.swing.GroupLayout(Encabezado);
        Encabezado.setLayout(EncabezadoLayout);
        EncabezadoLayout.setHorizontalGroup(
            EncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EncabezadoLayout.createSequentialGroup()
                .addContainerGap(156, Short.MAX_VALUE)
                .addComponent(Nombre_Encabezado, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(188, 188, 188))
        );
        EncabezadoLayout.setVerticalGroup(
            EncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EncabezadoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Nombre_Encabezado, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        jPanel2.add(Encabezado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 60));

        Cuerpo.setBackground(new java.awt.Color(153, 204, 255));

        Apellido_Paterno.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        Apellido_Paterno.setForeground(new java.awt.Color(0, 51, 51));
        Apellido_Paterno.setText("CITA  HORARIO (MATUTINO, VESPERTINO)");

        CURP.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        CURP.setForeground(new java.awt.Color(0, 51, 51));
        CURP.setText("CURP");

        Telefono.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        Telefono.setForeground(new java.awt.Color(0, 51, 51));
        Telefono.setText("ID DOCTOR (10 DÍGITOS)");

        txtCitaHorarioR.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtCitaHorarioR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCitaHorarioRActionPerformed(evt);
            }
        });

        txtCurpHorarioR.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtCurpHorarioR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCurpHorarioRActionPerformed(evt);
            }
        });

        txtIdDoctorHorarioR.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnRegistrarHorario.setBackground(new java.awt.Color(0, 153, 255));
        btnRegistrarHorario.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnRegistrarHorario.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarHorario.setText("REGISTRAR");
        btnRegistrarHorario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistrarHorarioMouseClicked(evt);
            }
        });
        btnRegistrarHorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarHorarioActionPerformed(evt);
            }
        });

        btnRegresarHorario.setBackground(new java.awt.Color(0, 153, 255));
        btnRegresarHorario.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnRegresarHorario.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresarHorario.setText("REGRESAR");
        btnRegresarHorario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegresarHorarioMouseClicked(evt);
            }
        });
        btnRegresarHorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarHorarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CuerpoLayout = new javax.swing.GroupLayout(Cuerpo);
        Cuerpo.setLayout(CuerpoLayout);
        CuerpoLayout.setHorizontalGroup(
            CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CuerpoLayout.createSequentialGroup()
                .addGroup(CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(CuerpoLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(Apellido_Paterno))
                    .addGroup(CuerpoLayout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(btnRegistrarHorario)
                        .addGap(44, 44, 44)
                        .addComponent(btnRegresarHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CuerpoLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(CuerpoLayout.createSequentialGroup()
                                .addComponent(Telefono)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtIdDoctorHorarioR, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(CuerpoLayout.createSequentialGroup()
                                .addComponent(CURP)
                                .addGroup(CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(CuerpoLayout.createSequentialGroup()
                                        .addGap(286, 286, 286)
                                        .addComponent(txtCitaHorarioR, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CuerpoLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtCurpHorarioR, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGap(33, 110, Short.MAX_VALUE))
        );
        CuerpoLayout.setVerticalGroup(
            CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CuerpoLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Apellido_Paterno)
                    .addComponent(txtCitaHorarioR, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CURP)
                    .addComponent(txtCurpHorarioR, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdDoctorHorarioR, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Telefono))
                .addGap(40, 40, 40)
                .addGroup(CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegresarHorario)
                    .addComponent(btnRegistrarHorario))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel2.add(Cuerpo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 650, 270));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void limpiarCajas(){
        txtCitaHorarioR.setText(null);
        txtCurpHorarioR.setText(null);
        txtIdDoctorHorarioR.setText(null);
    }
    private void txtCitaHorarioRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCitaHorarioRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCitaHorarioRActionPerformed

    private void txtCurpHorarioRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCurpHorarioRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCurpHorarioRActionPerformed

    private void btnRegistrarHorarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarHorarioMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarHorarioMouseClicked

    private void btnRegistrarHorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarHorarioActionPerformed
        Connection con = null;
        try {
            con = conectarBD.getConnection();
            conectarBD.ps = con.prepareStatement("INSERT INTO horario (Cita_Horario, CURP, Id_Doctor) VALUES (?, ?, ?)");
            conectarBD.ps.setString(1, txtCitaHorarioR.getText());
            conectarBD.ps.setString(2, txtCurpHorarioR.getText());
            conectarBD.ps.setString(3, txtIdDoctorHorarioR.getText());

            //EJECUTAR LA CONSULTA
            int res = conectarBD.ps.executeUpdate();
            if(res > 0){
                JOptionPane.showMessageDialog(null, "HORARIO GUARDADO");
                limpiarCajas();
            }else{
                JOptionPane.showMessageDialog(null, "ERROR AL GUARDAR HORARIO");
                limpiarCajas();
            }

            //CERRAR BD
            con.close();
        } catch (Exception e) {
            System.out.println("Error: "+e);
        }
    }//GEN-LAST:event_btnRegistrarHorarioActionPerformed

    private void btnRegresarHorarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarHorarioMouseClicked
        Principal_Administrador nuevaV = new Principal_Administrador();
        nuevaV.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarHorarioMouseClicked

    private void btnRegresarHorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarHorarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegresarHorarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro_HorarioAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro_HorarioAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro_HorarioAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro_HorarioAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro_HorarioAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Apellido_Paterno;
    private javax.swing.JLabel CURP;
    private javax.swing.JPanel Cuerpo;
    private javax.swing.JPanel Encabezado;
    private javax.swing.JLabel Nombre_Encabezado;
    private javax.swing.JLabel Telefono;
    private javax.swing.JButton btnRegistrarHorario;
    private javax.swing.JButton btnRegresarHorario;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtCitaHorarioR;
    private javax.swing.JTextField txtCurpHorarioR;
    private javax.swing.JTextField txtIdDoctorHorarioR;
    // End of variables declaration//GEN-END:variables
}
