/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;

import Clases.Conectar;
import java.sql.Connection;
import java.sql.Time;
import javax.swing.JOptionPane;

/**
 *
 * @author sandybau
 */
public class Registro_PacienteAdmin extends javax.swing.JFrame {
    Conectar conectarBD = new Conectar();
     //REALICE UNA NUEVA INSTANCIA DE LA CLASE DISPARADOR
    
    
    /**
     * Creates new form Registrar_PacienteAdmin
     */
    public Registro_PacienteAdmin() {
        initComponents();
        setLocationRelativeTo(null);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Encabezado = new javax.swing.JPanel();
        Nombre_Encabezado = new javax.swing.JLabel();
        Cuerpo = new javax.swing.JPanel();
        Nombre_Paciente = new javax.swing.JLabel();
        Apellido_Paterno = new javax.swing.JLabel();
        Apellido_Materno = new javax.swing.JLabel();
        CURP = new javax.swing.JLabel();
        Telefono = new javax.swing.JLabel();
        Hora_Entrada = new javax.swing.JLabel();
        Hora_Salida = new javax.swing.JLabel();
        txtApellidoPaternoPaciente = new javax.swing.JTextField();
        txtApellidoMaternoPaciente = new javax.swing.JTextField();
        txtCurpPaciente = new javax.swing.JTextField();
        txtTelefonoPaciente = new javax.swing.JTextField();
        txtHoraEntradaPaciente = new javax.swing.JTextField();
        txtHoraSalidaPaciente = new javax.swing.JTextField();
        btnRegistrarPaciente = new javax.swing.JButton();
        txtNombrePaciente = new javax.swing.JTextField();
        btnRegresarPaciente = new javax.swing.JButton();
        btnDisparadorPacientesA = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Encabezado.setBackground(new java.awt.Color(0, 153, 255));

        Nombre_Encabezado.setFont(new java.awt.Font("Segoe UI Black", 0, 20)); // NOI18N
        Nombre_Encabezado.setForeground(new java.awt.Color(255, 255, 255));
        Nombre_Encabezado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Nombre_Encabezado.setText("REGISTRO PACIENTES");

        javax.swing.GroupLayout EncabezadoLayout = new javax.swing.GroupLayout(Encabezado);
        Encabezado.setLayout(EncabezadoLayout);
        EncabezadoLayout.setHorizontalGroup(
            EncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EncabezadoLayout.createSequentialGroup()
                .addContainerGap(237, Short.MAX_VALUE)
                .addComponent(Nombre_Encabezado)
                .addGap(237, 237, 237))
        );
        EncabezadoLayout.setVerticalGroup(
            EncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EncabezadoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Nombre_Encabezado, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        jPanel1.add(Encabezado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 60));

        Cuerpo.setBackground(new java.awt.Color(153, 204, 255));

        Nombre_Paciente.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        Nombre_Paciente.setForeground(new java.awt.Color(0, 51, 51));
        Nombre_Paciente.setText("NOMBRE DEL PACIENTE");

        Apellido_Paterno.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        Apellido_Paterno.setForeground(new java.awt.Color(0, 51, 51));
        Apellido_Paterno.setText("APELLIDO PATERNO");

        Apellido_Materno.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        Apellido_Materno.setForeground(new java.awt.Color(0, 51, 51));
        Apellido_Materno.setText("APELLIDO MATERNO");

        CURP.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        CURP.setForeground(new java.awt.Color(0, 51, 51));
        CURP.setText("CURP");

        Telefono.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        Telefono.setForeground(new java.awt.Color(0, 51, 51));
        Telefono.setText("TELÉFONO");

        Hora_Entrada.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        Hora_Entrada.setForeground(new java.awt.Color(0, 51, 51));
        Hora_Entrada.setText("HORA DE ENTRADA (HH:MM:SS)");

        Hora_Salida.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        Hora_Salida.setForeground(new java.awt.Color(0, 51, 51));
        Hora_Salida.setText("HORA DE SALIDA (HH:MM:SS)");

        txtApellidoPaternoPaciente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtApellidoPaternoPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoPaternoPacienteActionPerformed(evt);
            }
        });

        txtApellidoMaternoPaciente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtCurpPaciente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtCurpPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCurpPacienteActionPerformed(evt);
            }
        });

        txtTelefonoPaciente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtHoraEntradaPaciente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtHoraSalidaPaciente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnRegistrarPaciente.setBackground(new java.awt.Color(0, 153, 255));
        btnRegistrarPaciente.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnRegistrarPaciente.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarPaciente.setText("REGISTRAR");
        btnRegistrarPaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistrarPacienteMouseClicked(evt);
            }
        });
        btnRegistrarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarPacienteActionPerformed(evt);
            }
        });

        txtNombrePaciente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtNombrePaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombrePacienteActionPerformed(evt);
            }
        });

        btnRegresarPaciente.setBackground(new java.awt.Color(0, 153, 255));
        btnRegresarPaciente.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnRegresarPaciente.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresarPaciente.setText("REGRESAR");
        btnRegresarPaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegresarPacienteMouseClicked(evt);
            }
        });
        btnRegresarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarPacienteActionPerformed(evt);
            }
        });

        btnDisparadorPacientesA.setBackground(new java.awt.Color(0, 153, 255));
        btnDisparadorPacientesA.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnDisparadorPacientesA.setForeground(new java.awt.Color(255, 255, 255));
        btnDisparadorPacientesA.setText("EJECUTAR DISPARADOR");
        btnDisparadorPacientesA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDisparadorPacientesAMouseClicked(evt);
            }
        });
        btnDisparadorPacientesA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisparadorPacientesAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CuerpoLayout = new javax.swing.GroupLayout(Cuerpo);
        Cuerpo.setLayout(CuerpoLayout);
        CuerpoLayout.setHorizontalGroup(
            CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CuerpoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Nombre_Paciente)
                    .addComponent(Apellido_Paterno)
                    .addComponent(Apellido_Materno)
                    .addComponent(CURP)
                    .addComponent(Telefono)
                    .addComponent(Hora_Entrada)
                    .addComponent(Hora_Salida))
                .addGap(40, 40, 40)
                .addGroup(CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNombrePaciente, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                    .addComponent(txtHoraSalidaPaciente)
                    .addComponent(txtHoraEntradaPaciente, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtTelefonoPaciente)
                    .addComponent(txtCurpPaciente)
                    .addComponent(txtApellidoMaternoPaciente)
                    .addComponent(txtApellidoPaternoPaciente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CuerpoLayout.createSequentialGroup()
                        .addGroup(CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnRegistrarPaciente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                            .addComponent(btnRegresarPaciente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CuerpoLayout.createSequentialGroup()
                        .addComponent(btnDisparadorPacientesA)
                        .addContainerGap())))
        );
        CuerpoLayout.setVerticalGroup(
            CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CuerpoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Nombre_Paciente)
                    .addComponent(txtNombrePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Apellido_Paterno)
                    .addComponent(txtApellidoPaternoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Apellido_Materno)
                    .addComponent(txtApellidoMaternoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CuerpoLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CURP)
                            .addComponent(txtCurpPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CuerpoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDisparadorPacientesA)
                        .addGap(12, 12, 12)))
                .addGroup(CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Telefono)
                    .addComponent(txtTelefonoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CuerpoLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Hora_Entrada)
                            .addComponent(txtHoraEntradaPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CuerpoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRegresarPaciente)
                        .addGap(51, 51, 51)))
                .addGroup(CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Hora_Salida)
                    .addComponent(txtHoraSalidaPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistrarPaciente))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel1.add(Cuerpo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 690, 390));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void limpiarCajas(){
        txtNombrePaciente.setText(null);
        txtApellidoPaternoPaciente.setText(null);
        txtApellidoMaternoPaciente.setText(null);
        txtCurpPaciente.setText(null);
        txtTelefonoPaciente.setText(null);
        txtHoraEntradaPaciente.setText(null);
        txtHoraSalidaPaciente.setText(null);
    }
    
    private void txtApellidoPaternoPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoPaternoPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoPaternoPacienteActionPerformed

    private void txtCurpPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCurpPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCurpPacienteActionPerformed

    private void btnRegistrarPacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarPacienteMouseClicked
        Connection con = null;
        try {
            con = conectarBD.getConnection();
            conectarBD.ps = con.prepareStatement("INSERT INTO paciente (Nombre_Paciente, Apellido_Paterno_Paciente, Apellido_Materno_Paciente, CURP, Telefono, Hora_Entrada, Hora_Salida) VALUES (?, ?, ?, ?, ?, ?, ?)");
            conectarBD.ps.setString(1, txtNombrePaciente.getText());
            conectarBD.ps.setString(2, txtApellidoPaternoPaciente.getText());
            conectarBD.ps.setString(3, txtApellidoMaternoPaciente.getText());
            conectarBD.ps.setString(4, txtCurpPaciente.getText());
            conectarBD.ps.setString(5, txtTelefonoPaciente.getText());
            conectarBD.ps.setTime(6,Time.valueOf(txtHoraEntradaPaciente.getText()));
            conectarBD.ps.setTime(7,Time.valueOf(txtHoraSalidaPaciente.getText()));

            //EJECUTAR LA CONSULTA
            int res = conectarBD.ps.executeUpdate();
            if(res > 0){
                JOptionPane.showMessageDialog(null, "PACIENTE GUARDADO");
                limpiarCajas();
            }
            else{
                JOptionPane.showMessageDialog(null, "ERROR AL GUARDAR PACIENTE");
                limpiarCajas();
            }
            //CERRAR BD
            con.close();
        } catch (Exception e) {
            System.err.println("Error: "+e);
        }
        
    }//GEN-LAST:event_btnRegistrarPacienteMouseClicked

    private void btnRegistrarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarPacienteActionPerformed

    private void txtNombrePacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombrePacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombrePacienteActionPerformed

    private void btnRegresarPacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarPacienteMouseClicked
        Principal_Administrador nuevaV = new Principal_Administrador();
        nuevaV.setVisible(true);
        //this.dispose();
    }//GEN-LAST:event_btnRegresarPacienteMouseClicked

    private void btnRegresarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegresarPacienteActionPerformed

    private void btnDisparadorPacientesAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDisparadorPacientesAMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDisparadorPacientesAMouseClicked

    private void btnDisparadorPacientesAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisparadorPacientesAActionPerformed
       //METODO PARA EL DISPARADOR
       /*USAR conectarBD.ps = con.prepareStatement("SELECT COUNT(Nombre_Paciente) FROM paciente;");*/
       Disparador_Contar_Paciente DisparadorCP = new Disparador_Contar_Paciente();
       DisparadorCP.setVisible(true);
       
       Connection con = null;
        try {
            
            con = conectarBD.getConnection();
            conectarBD.ps = con.prepareStatement("SELECT MAX(cantidad_pac) AS ultimoRegistro FROM cantidad_pacientes");

            conectarBD.rs = conectarBD.ps.executeQuery(); //TRAER LOS RESULTADOS DE LA CONSULTA
            if(conectarBD.rs.next()){
                Disparador_Contar_Paciente.txtCantidad_Pacientes.setText(conectarBD.rs.getString("ultimoRegistro"));
            }else{
                JOptionPane.showMessageDialog(null, "NO SE ENCONTRARON RESULTADOS");
            }
            
            //CERRAR BD
            con.close();
        } catch (Exception e) {
            System.out.println("Error: "+e);
        }
    }//GEN-LAST:event_btnDisparadorPacientesAActionPerformed

     //* @param args the command line arguments
    /**
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro_PacienteAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro_PacienteAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro_PacienteAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro_PacienteAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro_PacienteAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Apellido_Materno;
    private javax.swing.JLabel Apellido_Paterno;
    private javax.swing.JLabel CURP;
    private javax.swing.JPanel Cuerpo;
    private javax.swing.JPanel Encabezado;
    private javax.swing.JLabel Hora_Entrada;
    private javax.swing.JLabel Hora_Salida;
    private javax.swing.JLabel Nombre_Encabezado;
    private javax.swing.JLabel Nombre_Paciente;
    private javax.swing.JLabel Telefono;
    private javax.swing.JButton btnDisparadorPacientesA;
    private javax.swing.JButton btnRegistrarPaciente;
    private javax.swing.JButton btnRegresarPaciente;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtApellidoMaternoPaciente;
    private javax.swing.JTextField txtApellidoPaternoPaciente;
    private javax.swing.JTextField txtCurpPaciente;
    private javax.swing.JTextField txtHoraEntradaPaciente;
    private javax.swing.JTextField txtHoraSalidaPaciente;
    private javax.swing.JTextField txtNombrePaciente;
    private javax.swing.JTextField txtTelefonoPaciente;
    // End of variables declaration//GEN-END:variables
}
