/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;

/**
 *
 * @author rafae
 */
public class Transacciones extends javax.swing.JFrame {

    /**
     * Creates new form Transacciones
     */
    public Transacciones() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Encabezado = new javax.swing.JPanel();
        Nombre_Encabezado = new javax.swing.JLabel();
        Cuerpo = new javax.swing.JPanel();
        btnInsercionT = new javax.swing.JButton();
        btnRegresarDoctor = new javax.swing.JButton();
        btnActualizaciónT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Encabezado.setBackground(new java.awt.Color(0, 153, 255));
        Encabezado.setPreferredSize(new java.awt.Dimension(690, 60));

        Nombre_Encabezado.setFont(new java.awt.Font("Segoe UI Black", 0, 20)); // NOI18N
        Nombre_Encabezado.setForeground(new java.awt.Color(255, 255, 255));
        Nombre_Encabezado.setText("TRANSACCIONES DOCTOR");

        javax.swing.GroupLayout EncabezadoLayout = new javax.swing.GroupLayout(Encabezado);
        Encabezado.setLayout(EncabezadoLayout);
        EncabezadoLayout.setHorizontalGroup(
            EncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EncabezadoLayout.createSequentialGroup()
                .addGap(245, 245, 245)
                .addComponent(Nombre_Encabezado)
                .addContainerGap(184, Short.MAX_VALUE))
        );
        EncabezadoLayout.setVerticalGroup(
            EncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EncabezadoLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(Nombre_Encabezado)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel1.add(Encabezado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 60));

        Cuerpo.setBackground(new java.awt.Color(153, 204, 255));

        btnInsercionT.setBackground(new java.awt.Color(0, 153, 255));
        btnInsercionT.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnInsercionT.setForeground(new java.awt.Color(255, 255, 255));
        btnInsercionT.setText("INSERCIÓN");
        btnInsercionT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInsercionTMouseClicked(evt);
            }
        });
        btnInsercionT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsercionTActionPerformed(evt);
            }
        });

        btnRegresarDoctor.setBackground(new java.awt.Color(0, 153, 255));
        btnRegresarDoctor.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnRegresarDoctor.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresarDoctor.setText("REGRESAR");
        btnRegresarDoctor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegresarDoctorMouseClicked(evt);
            }
        });
        btnRegresarDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarDoctorActionPerformed(evt);
            }
        });

        btnActualizaciónT.setBackground(new java.awt.Color(0, 153, 255));
        btnActualizaciónT.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnActualizaciónT.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizaciónT.setText("ACTUALIZACIÓN");
        btnActualizaciónT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnActualizaciónTMouseClicked(evt);
            }
        });
        btnActualizaciónT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizaciónTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CuerpoLayout = new javax.swing.GroupLayout(Cuerpo);
        Cuerpo.setLayout(CuerpoLayout);
        CuerpoLayout.setHorizontalGroup(
            CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CuerpoLayout.createSequentialGroup()
                .addContainerGap(135, Short.MAX_VALUE)
                .addComponent(btnInsercionT, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(126, 126, 126)
                .addComponent(btnActualizaciónT, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(128, 128, 128))
            .addGroup(CuerpoLayout.createSequentialGroup()
                .addGap(280, 280, 280)
                .addComponent(btnRegresarDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        CuerpoLayout.setVerticalGroup(
            CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CuerpoLayout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizaciónT, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInsercionT, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addComponent(btnRegresarDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        jPanel1.add(Cuerpo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 690, 220));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsercionTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInsercionTMouseClicked
        
    }//GEN-LAST:event_btnInsercionTMouseClicked

    private void btnInsercionTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsercionTActionPerformed
        Registro_DoctorT transaccion = new Registro_DoctorT();
        transaccion.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnInsercionTActionPerformed

    private void btnRegresarDoctorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarDoctorMouseClicked
        Principal_Administrador nuevaV = new Principal_Administrador();
        nuevaV.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarDoctorMouseClicked

    private void btnRegresarDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarDoctorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegresarDoctorActionPerformed

    private void btnActualizaciónTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizaciónTMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnActualizaciónTMouseClicked

    private void btnActualizaciónTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizaciónTActionPerformed
        Actualizar_DoctorT transaccion = new Actualizar_DoctorT();
        transaccion.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnActualizaciónTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transacciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transacciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transacciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transacciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Transacciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Cuerpo;
    private javax.swing.JPanel Encabezado;
    private javax.swing.JLabel Nombre_Encabezado;
    private javax.swing.JButton btnActualizaciónT;
    private javax.swing.JButton btnInsercionT;
    private javax.swing.JButton btnRegresarDoctor;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
