/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;

import java.sql.Connection;
import javax.swing.JOptionPane;
import Clases.Conectar;

/**
 *
 * @author rafae
 */
public class ViewPerfilesA extends javax.swing.JFrame {
    Conectar conectarBD = new Conectar();
    /**
     * Creates new form ViewPerfiles
     */
    public ViewPerfilesA() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        background = new javax.swing.JPanel();
        Encabezado = new javax.swing.JPanel();
        JLabelTitulo = new javax.swing.JLabel();
        Nombre_Doctor = new javax.swing.JLabel();
        Apellido_Paterno = new javax.swing.JLabel();
        Apellido_Materno = new javax.swing.JLabel();
        Id_Doctor = new javax.swing.JLabel();
        txtEspecialidadG = new javax.swing.JLabel();
        btnRegresarPerfil = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtEspecialidadG1 = new javax.swing.JLabel();
        JLabelNombre = new javax.swing.JLabel();
        JLabelApellidos = new javax.swing.JLabel();
        JLabelCorreo = new javax.swing.JLabel();
        JLabelDireccion = new javax.swing.JLabel();
        JLabelTelefono = new javax.swing.JLabel();
        JLabelRol = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        background.setBackground(new java.awt.Color(153, 204, 255));

        Encabezado.setBackground(new java.awt.Color(0, 153, 255));

        JLabelTitulo.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        JLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        JLabelTitulo.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        javax.swing.GroupLayout EncabezadoLayout = new javax.swing.GroupLayout(Encabezado);
        Encabezado.setLayout(EncabezadoLayout);
        EncabezadoLayout.setHorizontalGroup(
            EncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EncabezadoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );
        EncabezadoLayout.setVerticalGroup(
            EncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EncabezadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLabelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        Nombre_Doctor.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        Nombre_Doctor.setForeground(new java.awt.Color(0, 51, 51));
        Nombre_Doctor.setText("NOMBRE:");

        Apellido_Paterno.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        Apellido_Paterno.setForeground(new java.awt.Color(0, 51, 51));
        Apellido_Paterno.setText("APELLIDOS:");

        Apellido_Materno.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        Apellido_Materno.setForeground(new java.awt.Color(0, 51, 51));
        Apellido_Materno.setText("DIRECCIÓN:");

        Id_Doctor.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        Id_Doctor.setForeground(new java.awt.Color(0, 51, 51));
        Id_Doctor.setText("TELÉFONO:");

        txtEspecialidadG.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        txtEspecialidadG.setForeground(new java.awt.Color(0, 51, 51));
        txtEspecialidadG.setText("CORREO:");

        btnRegresarPerfil.setBackground(new java.awt.Color(0, 153, 255));
        btnRegresarPerfil.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnRegresarPerfil.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresarPerfil.setText("REGRESAR");
        btnRegresarPerfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegresarPerfilMouseClicked(evt);
            }
        });
        btnRegresarPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarPerfilActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FotoAdmin.jpg"))); // NOI18N

        txtEspecialidadG1.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        txtEspecialidadG1.setForeground(new java.awt.Color(0, 51, 51));
        txtEspecialidadG1.setText("ROL:");

        JLabelNombre.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        JLabelNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        JLabelApellidos.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        JLabelApellidos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        JLabelCorreo.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        JLabelCorreo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        JLabelDireccion.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        JLabelDireccion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        JLabelTelefono.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        JLabelTelefono.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        JLabelRol.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        JLabelRol.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Encabezado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Nombre_Doctor, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Apellido_Paterno)
                            .addComponent(Apellido_Materno)
                            .addComponent(Id_Doctor)
                            .addComponent(txtEspecialidadG, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEspecialidadG1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JLabelRol, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JLabelCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JLabelApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JLabelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JLabelDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JLabelTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(btnRegresarPerfil)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(Encabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Nombre_Doctor)
                            .addComponent(JLabelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Apellido_Paterno)
                            .addComponent(JLabelApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Apellido_Materno)
                            .addComponent(JLabelDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Id_Doctor)
                            .addComponent(JLabelTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEspecialidadG)
                            .addComponent(JLabelCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEspecialidadG1)
                            .addComponent(JLabelRol, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRegresarPerfil)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(49, 49, 49))))
        );

        jPanel1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 370));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void consultarUsuario(String SESSION){
        String SESSIONU = SESSION;
        //System.out.println("VARIABLE SESION DESDE VIEWL ADMIN: "+SESSIONU);
        Connection con = null;
        try {
            con = conectarBD.getConnection();
            conectarBD.ps = con.prepareStatement("SELECT * FROM usuarios WHERE Identificador = ?");
            conectarBD.ps.setString(1, SESSIONU);

            conectarBD.rs = conectarBD.ps.executeQuery(); //TRAER LOS RESULTADOS DE LA CONSULTA
            if(conectarBD.rs.next()){
                JLabelNombre.setText(conectarBD.rs.getString("Nombre"));
                JLabelTitulo.setText(conectarBD.rs.getString("Nombre"));
                JLabelApellidos.setText(conectarBD.rs.getString("Apellidos"));
                JLabelDireccion.setText(conectarBD.rs.getString("Direccion"));
                JLabelTelefono.setText(conectarBD.rs.getString("Telefono"));
                JLabelCorreo.setText(conectarBD.rs.getString("Correo"));
                JLabelRol.setText(conectarBD.rs.getString("Rol"));
                

            }else{
                JOptionPane.showMessageDialog(null, "NO SE ENCONTRARON RESULTADOS");
            }
            //EJECUTAR LA CONSULTA
            int res = conectarBD.ps.executeUpdate();
            if(res > 0){
                //JOptionPane.showMessageDialog(null, "LOCALIZADO ");
                
            }
            else{
                //JOptionPane.showMessageDialog(null, "ERROR AL CONSULTAR");
            }
            //CERRAR BD
            con.close();
        } catch (Exception e) {
            
        }
    }
    private void btnRegresarPerfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarPerfilMouseClicked
       Principal_Administrador nuevaV = new Principal_Administrador();
        nuevaV.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarPerfilMouseClicked

    private void btnRegresarPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarPerfilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegresarPerfilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewPerfilesA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewPerfilesA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewPerfilesA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewPerfilesA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewPerfilesA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Apellido_Materno;
    private javax.swing.JLabel Apellido_Paterno;
    private javax.swing.JPanel Encabezado;
    private javax.swing.JLabel Id_Doctor;
    private javax.swing.JLabel JLabelApellidos;
    private javax.swing.JLabel JLabelCorreo;
    private javax.swing.JLabel JLabelDireccion;
    private javax.swing.JLabel JLabelNombre;
    private javax.swing.JLabel JLabelRol;
    private javax.swing.JLabel JLabelTelefono;
    private javax.swing.JLabel JLabelTitulo;
    private javax.swing.JLabel Nombre_Doctor;
    private javax.swing.JPanel background;
    private javax.swing.JButton btnRegresarPerfil;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel txtEspecialidadG;
    private javax.swing.JLabel txtEspecialidadG1;
    // End of variables declaration//GEN-END:variables
}
